/**
 * @fileOverview AccentCatalog is a component for OshbVerse,
 * to catalog cantillation marks.
 * @version 1.2
 * @author David
 */
accentCatalog = {
	"prose": {
		"disjunctive": {
			"\u05C3": {"name": "Sof Pasuq", "rank": "0", "final": "true"},
			"\u0596\u05C3": {"name": "Mëayla with Sof Pasuq", "rank": "0", "final": "true"},
			"\u05A5\u05C3": {"name": "Merkha with Sof Pasuq", "rank": "0", "final": "true"},
			"\u0591": {"name": "Atnach", "rank": "0"},
			"\u0596\u0591": {"name": "Mëayla with Atnach", "rank": "0"},
			"\u05A3\u0591": {"name": "Munnach with Atnach", "rank": "0"},
			"\u05A5\u0591": {"name": "Merkha with Atnach", "rank": "0"},
			"\u0591\u0599": {"name": "Atnach with Pashta", "rank": "0"},
			"\u0592": {"name": "Segol", "rank": "1"},
			"\u0593\u05C0": {"name": "Shalshelet", "rank": "1"},
			"\u0594": {"name": "Zaqef Qatan", "rank": "1"},
			"\u05A3\u0594": {"name": "Munnach with Zaqef Qatan", "rank": "1"},
			"\u05A8\u0594": {"name": "Qadma with Zaqef Qatan", "rank": "1"},
			"\u0595": {"name": "Zaqef Gadol", "rank": "1"},
			"\u0596": {"name": "Tipcha", "rank": "1", "final": "true"},
			"\u05A5\u0596": {"name": "Merkha with Tipcha", "rank": "1", "final": "true"},
			"\u0597": {"name": "Revia", "rank": "2"},
			"\u05A0\u0597": {"name": "Telisha Gedola with Revia", "rank": "2"},
			"\u05A3\u0597": {"name": "Munnach with Revia", "rank": "2"},
			"\u05AE": {"name": "Zarqa", "rank": "2", "final": "true"},
			"\u0598\u05AE": {"name": "Zarqa", "rank": "2", "final": "true"},
			"\u0599": {"name": "Pashta", "rank": "2", "final": "true"},
			"\u0599\u0599": {"name": "Pashta", "rank": "2", "final": "true"},
			"\u05A8\u0599": {"name": "Pashta", "rank": "2", "final": "true"},
			"\u05A4\u0599": {"name": "Mahpakh with Pashta", "rank": "2", "final": "true"},
			"\u05A4\u0599\u0599": {"name": "Mahpakh with Pashta", "rank": "2", "final": "true"},
			"\u05A4\u05A8\u0599": {"name": "Mahpakh with Pashta", "rank": "2", "final": "true"},
			"\u059A": {"name": "Yetiv", "rank": "2", "final": "true"},
			"\u059B": {"name": "Tevir", "rank": "2", "final": "true"},
			"\u05A5\u059B": {"name": "Merkha with Tevir", "rank": "2", "final": "true"},
			"\u05A1": {"name": "Pazer", "rank": "3"},
			"\u05A3\u05A1": {"name": "Munnach with Pazer", "rank": "3"},
			"\u059F": {"name": "Qarney Para", "rank": "3"},
			"\u05A0": {"name": "Telisha Gedola", "rank": "3"},
			"\u05A0\u05A0": {"name": "Telisha Gedola", "rank": "3"},
			"\u059D\u05A0": {"name": "Geresh Muqdam with Telisha Gedola", "rank": "3", "final": "true"},
			"\u059C": {"name": "Geresh", "rank": "3", "final": "true"},
			"\u05A0\u059C": {"name": "Telisha Gedola with Geresh", "rank": "3", "final": "true"},
			"\u05A8\u059C": {"name": "Qadma with Geresh", "rank": "3", "final": "true"},
			"\u059D": {"name": "Geresh Muqdam", "rank": "3", "final": "true"},
			"\u059E": {"name": "Gershayim", "rank": "3", "final": "true"},
			"\u05A0\u059E": {"name": "Telisha Gedola with Gershayim", "rank": "3", "final": "true"},
			"\u059E\u05A0": {"name": "Gershayim with Telisha Gedola", "rank": "3", "final": "true"},
			"\u05A3\u05C0": {"name": "Legarmeh", "rank": "3", "final": "true"}
		},
		"conjunctive": {
			"\u05C0": {"name": "Paseq", "rank": "4"},
			"\u05A5\u05A3\u05C0": {"name": "Merkha and Munnach with Paseq", "rank": "4"},
			"\u05A4\u05C0": {"name": "Mahpakh with Paseq", "rank": "4"},
			"\u05A5\u05C0": {"name": "Merkha with Paseq", "rank": "4"},
			"\u05A7\u05C0": {"name": "Darga with Paseq", "rank": "4"},
			"\u05A8\u05C0": {"name": "Qadma with Paseq", "rank": "4"},
			"\u05A8\u05A5\u05C0": {"name": "Qadma and Merkha with Paseq", "rank": "4"},
			"\u05A9\u05C0": {"name": "Telisha Qetana with Paseq", "rank": "4"},
			"\u05A3": {"name": "Munnach", "rank": "4"},
			"\u05A3\u05A3": {"name": "Munnach with Munnach", "rank": "4"},
			"\u05AA": {"name": "Galgal", "rank": "4"},
			"\u05A5": {"name": "Merkha", "rank": "4"},
			"\u05A8\u05A5": {"name": "Qadma with Merkha", "rank": "4"},
			"\u05A9": {"name": "Telisha Qetana", "rank": "4"},
			"\u05A9\u05A9": {"name": "Telisha Qetana", "rank": "4"},
			"\u05A8": {"name": "Qadma", "rank": "4"},
			"\u05A4": {"name": "Mahpakh", "rank": "4"},
			"\u05A3\u05A4": {"name": "Munnach with Mahpakh", "rank": "4"},
			"\u05A8\u05A4": {"name": "Qadma with Mahpakh", "rank": "4"},
			"\u05A6": {"name": "Merkha Khefula", "rank": "4"},
			"\u05A7": {"name": "Darga", "rank": "4"},
			"\u05A8\u05A7": {"name": "Qadma with Darga", "rank": "4"},
			"\u05BE": {"name": "Maqqef", "rank": "4"},
			"\u05BD": {"name": "Meteg", "rank": "4"},
			"": {"name": "None", "rank": "5"}
		}
	},
	"poetic": {
		"disjunctive": {
			"\u05C3": {"name": "Sof Pasuq", "rank": "0", "final": "true"},
			"\u05A5\u05C3": {"name": "Merkha with Sof Pasuq", "rank": "0", "final": "true"},
			"\u0591": {"name": "Atnach", "rank": "1", "final": "true"},
			"\u05A3\u0591": {"name": "Munnach with Atnach", "rank": "1", "final": "true"},
			"\u05A5\u0591": {"name": "Merkha with Atnach", "rank": "1", "final": "true"},
			"\u0592": {"name": "Segol", "rank": "1"},
			"\u0593\u05C0": {"name": "Shalshelet Gedola", "rank": "1", "final": "true"},
			"\u0594": {"name": "Zaqef Qatan", "rank": "1"},
			"\u05A3\u0594": {"name": "Munnach with Zaqef Qatan", "rank": "1"},
			"\u0595": {"name": "Zaqef Gadol", "rank": "1"},
			"\u0597": {"name": "Revia", "rank": "1", "final": "true"},
			"\u059D\u0597": {"name": "Revia Mugrash", "rank": "1", "final": "true"},
			"\u05A5\u0597": {"name": "Merkha with Revia", "rank": "1", "final": "true"},
			"\u059D\u05A5\u0597": {"name": "Merkha with Revia Mugrash", "rank": "1", "final": "true"},
			"\u0598\u05A4\u0597": {"name": "Mahpakh Metsunnar with Revia", "rank": "1", "final": "true"},
			"\u05AD\u0597": {"name": "Dechi with Revia", "rank": "1", "final": "true"},
			"\u05A1": {"name": "Pazer", "rank": "1", "final": "true"},
			"\u05A1\u05C0": {"name": "Pazer with Paseq", "rank": "1", "final": "true"},
			"\u05AA\u05A1": {"name": "Galgal with Pazer", "rank": "1", "final": "true"},
			"\u05A4\u05C0": {"name": "Mahpakh Legarmeh", "rank": "1", "final": "true"},
			"\u05AB": {"name": "Ole", "rank": "1"},
			"\u05A4\u05AB": {"name": "Mahpakh with Ole", "rank": "1"},
			"\u05AB\u05A5": {"name": "Ole We Yored", "rank": "1"},
			"\u05AA\u05AB\u05A5": {"name": "Galgal with Ole We Yored", "rank": "1"},
			"\u05A5": {"name": "Yored", "rank": "1"},
			"\u05A8\u05C0": {"name": "Azla Legarmeh", "rank": "1"},
			"\u05A4\u05A8\u05C0": {"name": "Mahpakh with Azla Legarmeh", "rank": "1"},
			"\u0599": {"name": "Pashta", "rank": "2", "final": "true"},
			"\u0599\u0599": {"name": "Pashta", "rank": "2", "final": "true"},
			"\u05A8\u0599": {"name": "Pashta", "rank": "2", "final": "true"},
			"\u059A": {"name": "Yetiv", "rank": "2", "final": "true"},
			"\u059B": {"name": "Tevir", "rank": "2", "final": "true"},
			"\u05AD": {"name": "Dechi", "rank": "2", "final": "true"},
			"\u05AE": {"name": "Tsinnor", "rank": "2", "final": "true"},
			"\u05A0": {"name": "Telisha Gedola", "rank": "3"},
			"\u059C": {"name": "Geresh", "rank": "3", "final": "true"},
			"\u059D": {"name": "Geresh Muqdam", "rank": "3", "final": "true"},
			"\u059E": {"name": "Gershayim", "rank": "3", "final": "true"}
		},
		"conjunctive": {
			"\u05AB": {"name": "Ole", "rank": "1"},
			"\u05A4\u05AB": {"name": "Mahpakh with Ole", "rank": "1"},
			"\u05C0": {"name": "Paseq", "rank": "4"},
			"\u05A3": {"name": "Munnach", "rank": "4"},
			"\u0596\u05A3": {"name": "Tarcha with Munnach", "rank": "4"},
			"\u05A3\u05A3": {"name": "Munnach", "rank": "4"},
			"\u05A4\u05A3": {"name": "Mahpakh with Munnach", "rank": "4"},
			"\u05A3\u05A5": {"name": "Munnach with Merkha", "rank": "4"},
			"\u05A3\u05C0": {"name": "Munnach with Paseq", "rank": "4"},
			"\u05A4\u05A3\u05C0": {"name": "Mahpakh and Munnach with Paseq", "rank": "4"},
			"\u05AD\u05A3": {"name": "Dechi with Munnach", "rank": "4"},
			"\u05A3\u05AD": {"name": "Dechi with Munnach", "rank": "4"},
			"\u05A5\u05A8": {"name": "Merkha with Qadma", "rank": "4"},
			"\u05A7": {"name": "Darga", "rank": "4"},
			"\u05A8\u05A7": {"name": "Qadma with Darga", "rank": "4"},
			"\u05A9": {"name": "Telisha Qetana", "rank": "4"},
			"\u05AA": {"name": "Atnach Hafukh", "rank": "4"},
			"\u05AA\u05AB": {"name": "Galgal with Ole", "rank": "4"},
			"\u05AA\u05C0": {"name": "Galgal with Paseq", "rank": "4"},
			"\u05A5": {"name": "Merkha", "rank": "4"},
			"\u05A5\u05A5": {"name": "Merkha", "rank": "4"},
			"\u05A5\u05C0": {"name": "Merkha with Paseq", "rank": "4"},
			"\u0598\u05A5": {"name": "Merkha Metsunneret", "rank": "4"},
			"\u0598\u05A5\u05C0": {"name": "Tsinnorit and Merkha with Paseq", "rank": "4"},
			"\u05A5\u05A8\u05C0": {"name": "Merkha and Qadma with Paseq", "rank": "4"},
			"\u05AD\u05A5": {"name": "Dechi with Merkha", "rank": "4"},
			"\u0598": {"name": "Tsinnorit", "rank": "4"},
			"\u0593": {"name": "Shalshelet Qetana", "rank": "4"},
			"\u0596": {"name": "Tarcha", "rank": "4"},
			"\u05A8": {"name": "Qadma", "rank": "4"},
			"\u05AC": {"name": "Illuy", "rank": "4"},
			"\u05AC\u05C0": {"name": "Illuy with Paseq", "rank": "4"},
			"\u05AC\u05A8\u05C0": {"name": "Illuy and Qadma with Paseq", "rank": "4"},
			"\u05A4": {"name": "Mahpakh", "rank": "4"},
			"\u0598\u05A4": {"name": "Mahpakh Metsunnar", "rank": "4"},
			"\u05A4\u05A5": {"name": "Mahpakh with Merkha", "rank": "4"},
			"\u05BE": {"name": "Maqqef", "rank": "4"},
			"\u05BD": {"name": "Meteg", "rank": "4"},
			"": {"name": "None", "rank": "5"}
		}
	}
};