chapter0 = '<?xml version="1.0" encoding="UTF-8"?>';
chapter0 += '<chapter osisID="Gen.1">';
chapter0 += '  <verse osisID="Gen.1.1">';
chapter0 += '    <w lemma="b/7225" n="1.0" morph="HR/Ncfsa">בְּ/רֵאשִׁ֖ית</w>';
chapter0 += '    <w lemma="1254 a" morph="HVqp3ms">בָּרָ֣א</w>';
chapter0 += '    <w lemma="430" n="1" morph="HNcmpa">אֱלֹהִ֑ים</w>';
chapter0 += '    <w lemma="853" morph="HTo">אֵ֥ת</w>';
chapter0 += '    <w lemma="d/8064" n="0.0" morph="HTd/Ncmpa">הַ/שָּׁמַ֖יִם</w>';
chapter0 += '    <w lemma="c/853" morph="HC/To">וְ/אֵ֥ת</w>';
chapter0 += '    <w lemma="d/776" n="0" morph="HTd/Ncfsa">הָ/אָֽרֶץ</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.2">';
chapter0 += '    <w lemma="c/d/776" n="1.1.1" morph="HC/Td/Ncfsa">וְ/הָ/אָ֗רֶץ</w>';
chapter0 += '    <w lemma="1961" morph="HVqp3fs">הָיְתָ֥ה</w>';
chapter0 += '    <w lemma="8414" n="1.1.0" morph="HNcmsa">תֹ֨הוּ֙</w>';
chapter0 += '    <w lemma="c/922" n="1.1" morph="HC/Ncmsa">וָ/בֹ֔הוּ</w>';
chapter0 += '    <w lemma="c/2822" n="1.0" morph="HC/Ncmsa">וְ/חֹ֖שֶׁךְ</w>';
chapter0 += '    <w lemma="5921 a" morph="HR">עַל</w><seg type="x-maqqef">־</seg><w lemma="6440" morph="HNcmpc">פְּנֵ֣י</w>';
chapter0 += '    <w lemma="8415" n="1" morph="HNcmsa">תְה֑וֹם</w>';
chapter0 += '    <w lemma="c/7307" morph="HC/Ncfsc">וְ/ר֣וּחַ</w>';
chapter0 += '    <w lemma="430" n="0.1" morph="HNcmpa">אֱלֹהִ֔ים</w>';
chapter0 += '    <w lemma="7363 b" n="0.0" morph="HVprfsa">מְרַחֶ֖פֶת</w>';
chapter0 += '    <w lemma="5921 a" morph="HR">עַל</w><seg type="x-maqqef">־</seg><w lemma="6440" morph="HNcmpc">פְּנֵ֥י</w>';
chapter0 += '    <w lemma="d/4325" n="0" morph="HTd/Ncmda">הַ/מָּֽיִם</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.3">';
chapter0 += '    <w lemma="c/559">וַ/יֹּ֥אמֶר</w>';
chapter0 += '    <w lemma="430" n="1.0">אֱלֹהִ֖ים</w>';
chapter0 += '    <w lemma="1961">יְהִ֣י</w>';
chapter0 += '    <w lemma="216" n="1">א֑וֹר</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="216" n="0">אֽוֹר</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.4">';
chapter0 += '    <w lemma="c/7200">וַ/יַּ֧רְא</w>';
chapter0 += '    <w lemma="430" n="1.0.0">אֱלֹהִ֛ים</w>';
chapter0 += '    <w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/216" n="1.0">הָ/א֖וֹר</w>';
chapter0 += '    <w lemma="3588 a">כִּי</w><seg type="x-maqqef">־</seg><w lemma="2896 a" n="1" morph="HNcmsa">ט֑וֹב</w>';
chapter0 += '    <w lemma="c/914">וַ/יַּבְדֵּ֣ל</w>';
chapter0 += '    <w lemma="430" n="0.1">אֱלֹהִ֔ים</w>';
chapter0 += '    <w lemma="996">בֵּ֥ין</w>';
chapter0 += '    <w lemma="d/216" n="0.0">הָ/א֖וֹר</w>';
chapter0 += '    <w lemma="c/996">וּ/בֵ֥ין</w>';
chapter0 += '    <w lemma="d/2822" n="0">הַ/חֹֽשֶׁךְ</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.5">';
chapter0 += '    <w lemma="c/7121">וַ/יִּקְרָ֨א</w>';
chapter0 += '    <w lemma="430">אֱלֹהִ֤ים</w>';
chapter0 += '    <seg type="x-paseq">׀</seg>';
chapter0 += '    <w lemma="l/216" n="1.1.0">לָ/אוֹר֙</w>';
chapter0 += '    <w lemma="3117" n="1.1">י֔וֹם</w>';
chapter0 += '    <w lemma="c/l/2822" n="1.0">וְ/לַ/חֹ֖שֶׁךְ</w>';
chapter0 += '    <w lemma="7121">קָ֣רָא</w>';
chapter0 += '    <w lemma="3915" n="1">לָ֑יְלָה</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="6153">עֶ֥רֶב</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="1242" n="0.0">בֹ֖קֶר</w>';
chapter0 += '    <w lemma="3117">י֥וֹם</w>';
chapter0 += '    <w lemma="259" n="0">אֶחָֽד</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '    <seg type="x-pe">פ</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.6">';
chapter0 += '    <w lemma="c/559">וַ/יֹּ֣אמֶר</w>';
chapter0 += '    <w lemma="430" n="1.1">אֱלֹהִ֔ים</w>';
chapter0 += '    <w lemma="1961">יְהִ֥י</w>';
chapter0 += '    <w lemma="7549" n="1.0">רָקִ֖יעַ</w>';
chapter0 += '    <w lemma="b/8432">בְּ/ת֣וֹךְ</w>';
chapter0 += '    <w lemma="d/4325" n="1">הַ/מָּ֑יִם</w>';
chapter0 += '    <w lemma="c/1961">וִ/יהִ֣י</w>';
chapter0 += '    <w lemma="914" n="0.1">מַבְדִּ֔יל</w>';
chapter0 += '    <w lemma="996">בֵּ֥ין</w>';
chapter0 += '    <w lemma="4325" n="0.0">מַ֖יִם</w>';
chapter0 += '    <w lemma="l/4325" n="0">לָ/מָֽיִם</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.7">';
chapter0 += '    <w lemma="c/6213 a">וַ/יַּ֣עַשׂ</w>';
chapter0 += '    <w lemma="430" n="1.3.0">אֱלֹהִים֮</w>';
chapter0 += '    <w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/7549" n="1.3">הָ/רָקִיעַ֒</w>';
chapter0 += '    <w lemma="c/914" n="1.2.2">וַ/יַּבְדֵּ֗ל</w>';
chapter0 += '    <w lemma="996">בֵּ֤ין</w>';
chapter0 += '    <w lemma="d/4325" n="1.2.1">הַ/מַּ֨יִם֙</w>';
chapter0 += '    <w lemma="834 a" n="1.2.0">אֲשֶׁר֙</w>';
chapter0 += '    <w lemma="m/8478">מִ/תַּ֣חַת</w>';
chapter0 += '    <w lemma="l/7549" n="1.2">לָ/רָקִ֔יעַ</w>';
chapter0 += '    <w lemma="c/996">וּ/בֵ֣ין</w>';
chapter0 += '    <w lemma="d/4325" n="1.1">הַ/מַּ֔יִם</w>';
chapter0 += '    <w lemma="834 a" n="1.0">אֲשֶׁ֖ר</w>';
chapter0 += '    <w lemma="m/5921 a">מֵ/עַ֣ל</w>';
chapter0 += '    <w lemma="l/7549" n="1">לָ/רָקִ֑יעַ</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="3651 c" n="0">כֵֽן</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.8">';
chapter0 += '    <w lemma="c/7121">וַ/יִּקְרָ֧א</w>';
chapter0 += '    <w lemma="430" n="1.0.0">אֱלֹהִ֛ים</w>';
chapter0 += '    <w lemma="l/7549" n="1.0">לָֽ/רָקִ֖יעַ</w>';
chapter0 += '    <w lemma="8064" n="1">שָׁמָ֑יִם</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="6153">עֶ֥רֶב</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="1242" n="0.0">בֹ֖קֶר</w>';
chapter0 += '    <w lemma="3117">י֥וֹם</w>';
chapter0 += '    <w lemma="8145" n="0">שֵׁנִֽי</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '    <seg type="x-pe">פ</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.9">';
chapter0 += '    <w lemma="c/559">וַ/יֹּ֣אמֶר</w>';
chapter0 += '    <w lemma="430" n="1.1.1">אֱלֹהִ֗ים</w>';
chapter0 += '    <w lemma="6960 b">יִקָּו֨וּ</w>';
chapter0 += '    <w lemma="d/4325" n="1.1.0.0">הַ/מַּ֜יִם</w>';
chapter0 += '    <w lemma="m/8478">מִ/תַּ֤חַת</w>';
chapter0 += '    <w lemma="d/8064" n="1.1.0">הַ/שָּׁמַ֨יִם֙</w>';
chapter0 += '    <w lemma="413">אֶל</w><seg type="x-maqqef">־</seg><w lemma="4725">מָק֣וֹם</w>';
chapter0 += '    <w lemma="259" n="1.1">אֶחָ֔ד</w>';
chapter0 += '    <w lemma="c/7200" n="1.0">וְ/תֵרָאֶ֖ה</w>';
chapter0 += '    <w lemma="d/3004" n="1">הַ/יַּבָּשָׁ֑ה</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="3651 c" n="0">כֵֽן</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.10">';
chapter0 += '    <w lemma="c/7121">וַ/יִּקְרָ֨א</w>';
chapter0 += '    <w lemma="430">אֱלֹהִ֤ים</w>';
chapter0 += '    <seg type="x-paseq">׀</seg>';
chapter0 += '    <w lemma="l/3004" n="1.1.0">לַ/יַּבָּשָׁה֙</w>';
chapter0 += '    <w lemma="776" n="1.1">אֶ֔רֶץ</w>';
chapter0 += '    <w lemma="c/l/4723 c">וּ/לְ/מִקְוֵ֥ה</w>';
chapter0 += '    <w lemma="d/4325" n="1.0">הַ/מַּ֖יִם</w>';
chapter0 += '    <w lemma="7121">קָרָ֣א</w>';
chapter0 += '    <w lemma="3220" n="1">יַמִּ֑ים</w>';
chapter0 += '    <w lemma="c/7200">וַ/יַּ֥רְא</w>';
chapter0 += '    <w lemma="430" n="0.0">אֱלֹהִ֖ים</w>';
chapter0 += '    <w lemma="3588 a">כִּי</w><seg type="x-maqqef">־</seg><w lemma="2896 a" n="0">טֽוֹב</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.11">';
chapter0 += '    <w lemma="c/559">וַ/יֹּ֣אמֶר</w>';
chapter0 += '    <w lemma="430" n="1.3.1">אֱלֹהִ֗ים</w>';
chapter0 += '    <w lemma="1876">תַּֽדְשֵׁ֤א</w>';
chapter0 += '    <w lemma="d/776" n="1.3.0">הָ/אָ֨רֶץ֙</w>';
chapter0 += '    <w lemma="1877" n="1.3">דֶּ֔שֶׁא</w>';
chapter0 += '    <w lemma="6212" n="1.2.0">עֵ֚שֶׂב</w>';
chapter0 += '    <w lemma="2232">מַזְרִ֣יעַ</w>';
chapter0 += '    <w lemma="2233" n="1.2">זֶ֔רַע</w>';
chapter0 += '    <w lemma="6086">עֵ֣ץ</w>';
chapter0 += '    <w lemma="6529" n="1.1.0.0">פְּרִ֞י</w>';
chapter0 += '    <w lemma="6213 a">עֹ֤שֶׂה</w>';
chapter0 += '    <w lemma="6529" n="1.1.0">פְּרִי֙</w>';
chapter0 += '    <w lemma="l/4327" n="1.1">לְ/מִינ֔/וֹ</w>';
chapter0 += '    <w lemma="834 a">אֲשֶׁ֥ר</w>';
chapter0 += '    <w lemma="2233">זַרְע/וֹ</w><seg type="x-maqqef">־</seg><w lemma="b" n="1.0">ב֖/וֹ</w>';
chapter0 += '    <w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="1">הָ/אָ֑רֶץ</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="3651 c" n="0">כֵֽן</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.12">';
chapter0 += '    <w lemma="c/3318">וַ/תּוֹצֵ֨א</w>';
chapter0 += '    <w lemma="d/776" n="1.1.0.1">הָ/אָ֜רֶץ</w>';
chapter0 += '    <w lemma="1877" n="1.1.0.0">דֶּ֠שֶׁא</w>';
chapter0 += '    <w lemma="6212">עֵ֣שֶׂב</w>';
chapter0 += '    <w lemma="2232">מַזְרִ֤יעַ</w>';
chapter0 += '    <w lemma="2233" n="1.1.0">זֶ֨רַע֙</w>';
chapter0 += '    <w lemma="l/4327" n="1.1">לְ/מִינֵ֔/הוּ</w>';
chapter0 += '    <w lemma="c/6086">וְ/עֵ֧ץ</w>';
chapter0 += '    <w lemma="6213 a">עֹֽשֶׂה</w><seg type="x-maqqef">־</seg><w lemma="6529" n="1.0.0">פְּרִ֛י</w>';
chapter0 += '    <note n="c">We read one or more accents in L differently than BHS. Often this notation indicates a typographical error in BHS. </note>';
chapter0 += '    <note n="p">We read punctuation in L differently from BHS. </note>';
chapter0 += '    <w lemma="834 a">אֲשֶׁ֥ר</w>';
chapter0 += '    <w lemma="2233">זַרְע/וֹ</w><seg type="x-maqqef">־</seg><w lemma="b" n="1.0">ב֖/וֹ</w>';
chapter0 += '    <w lemma="l/4327" n="1">לְ/מִינֵ֑/הוּ</w>';
chapter0 += '    <w lemma="c/7200">וַ/יַּ֥רְא</w>';
chapter0 += '    <w lemma="430" n="0.0">אֱלֹהִ֖ים</w>';
chapter0 += '    <w lemma="3588 a">כִּי</w><seg type="x-maqqef">־</seg><w lemma="2896 a" n="0">טֽוֹב</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.13">';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="6153">עֶ֥רֶב</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="1242" n="0.0">בֹ֖קֶר</w>';
chapter0 += '    <w lemma="3117">י֥וֹם</w>';
chapter0 += '    <w lemma="7992" n="0">שְׁלִישִֽׁי</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '    <seg type="x-pe">פ</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.14">';
chapter0 += '    <w lemma="c/559">וַ/יֹּ֣אמֶר</w>';
chapter0 += '    <w lemma="430" n="1.2.1">אֱלֹהִ֗ים</w>';
chapter0 += '    <w lemma="1961">יְהִ֤י</w>';
chapter0 += '    <w lemma="3974" n="1.2.0">מְאֹרֹת֙</w>';
chapter0 += '    <w lemma="b/7549">בִּ/רְקִ֣יעַ</w>';
chapter0 += '    <w lemma="d/8064" n="1.2">הַ/שָּׁמַ֔יִם</w>';
chapter0 += '    <w lemma="l/914" n="1.1">לְ/הַבְדִּ֕יל</w>';
chapter0 += '    <w lemma="996">בֵּ֥ין</w>';
chapter0 += '    <w lemma="d/3117" n="1.0">הַ/יּ֖וֹם</w>';
chapter0 += '    <w lemma="c/996">וּ/בֵ֣ין</w>';
chapter0 += '    <w lemma="d/3915" n="1">הַ/לָּ֑יְלָה</w>';
chapter0 += '    <w lemma="c/1961">וְ/הָי֤וּ</w>';
chapter0 += '    <w lemma="l/226" n="0.1.0">לְ/אֹתֹת֙</w>';
chapter0 += '    <w lemma="c/l/4150" n="0.1">וּ/לְ/מ֣וֹעֲדִ֔ים</w>';
chapter0 += '    <w lemma="c/l/3117" n="0.0">וּ/לְ/יָמִ֖ים</w>';
chapter0 += '    <w lemma="c/8141" n="0">וְ/שָׁנִֽים</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.15">';
chapter0 += '    <w lemma="c/1961">וְ/הָי֤וּ</w>';
chapter0 += '    <w lemma="l/3974" n="1.1.0">לִ/מְאוֹרֹת֙</w>';
chapter0 += '    <w lemma="b/7549">בִּ/רְקִ֣יעַ</w>';
chapter0 += '    <w lemma="d/8064" n="1.1">הַ/שָּׁמַ֔יִם</w>';
chapter0 += '    <w lemma="l/215" n="1.0">לְ/הָאִ֖יר</w>';
chapter0 += '    <w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="1">הָ/אָ֑רֶץ</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="3651 c" n="0">כֵֽן</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.16">';
chapter0 += '    <w lemma="c/6213 a">וַ/יַּ֣עַשׂ</w>';
chapter0 += '    <w lemma="430" n="1.1">אֱלֹהִ֔ים</w>';
chapter0 += '    <w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="8147">שְׁנֵ֥י</w>';
chapter0 += '    <w lemma="d/3974" n="1.0">הַ/מְּאֹרֹ֖ת</w>';
chapter0 += '    <w lemma="d/1419 a" n="1">הַ/גְּדֹלִ֑ים</w>';
chapter0 += '    <w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/3974">הַ/מָּא֤וֹר</w>';
chapter0 += '    <w lemma="d/1419 a" n="0.2.0">הַ/גָּדֹל֙</w>';
chapter0 += '    <w lemma="l/4475">לְ/מֶמְשֶׁ֣לֶת</w>';
chapter0 += '    <w lemma="d/3117" n="0.2">הַ/יּ֔וֹם</w>';
chapter0 += '    <w lemma="c/853">וְ/אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/3974">הַ/מָּא֤וֹר</w>';
chapter0 += '    <w lemma="d/6996 b" n="0.1.0">הַ/קָּטֹן֙</w>';
chapter0 += '    <w lemma="l/4475">לְ/מֶמְשֶׁ֣לֶת</w>';
chapter0 += '    <w lemma="d/3915" n="0.1">הַ/לַּ֔יְלָה</w>';
chapter0 += '    <w lemma="c/853" n="0.0">וְ/אֵ֖ת</w>';
chapter0 += '    <w lemma="d/3556" n="0">הַ/כּוֹכָבִֽים</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.17">';
chapter0 += '    <w lemma="c/5414">וַ/יִּתֵּ֥ן</w>';
chapter0 += '    <w lemma="853" n="1.0.0">אֹתָ֛/ם</w>';
chapter0 += '    <w lemma="430" n="1.0">אֱלֹהִ֖ים</w>';
chapter0 += '    <w lemma="b/7549">בִּ/רְקִ֣יעַ</w>';
chapter0 += '    <w lemma="d/8064" n="1">הַ/שָּׁמָ֑יִם</w>';
chapter0 += '    <w lemma="l/215" n="0.0">לְ/הָאִ֖יר</w>';
chapter0 += '    <w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="0">הָ/אָֽרֶץ</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.18">';
chapter0 += '    <w lemma="c/l/4910" n="1.2.0">וְ/לִ/מְשֹׁל֙</w>';
chapter0 += '    <w lemma="b/3117">בַּ/יּ֣וֹם</w>';
chapter0 += '    <w lemma="c/b/3915" n="1.2">וּ/בַ/לַּ֔יְלָה</w>';
chapter0 += '    <w lemma="c/l/914" n="1.1">וּֽ/לֲ/הַבְדִּ֔יל</w>';
chapter0 += '    <w lemma="996">בֵּ֥ין</w>';
chapter0 += '    <w lemma="d/216" n="1.0">הָ/א֖וֹר</w>';
chapter0 += '    <w lemma="c/996">וּ/בֵ֣ין</w>';
chapter0 += '    <w lemma="d/2822" n="1">הַ/חֹ֑שֶׁךְ</w>';
chapter0 += '    <w lemma="c/7200">וַ/יַּ֥רְא</w>';
chapter0 += '    <w lemma="430" n="0.0">אֱלֹהִ֖ים</w>';
chapter0 += '    <w lemma="3588 a">כִּי</w><seg type="x-maqqef">־</seg><w lemma="2896 a" n="0">טֽוֹב</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.19">';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="6153">עֶ֥רֶב</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="1242" n="0.0">בֹ֖קֶר</w>';
chapter0 += '    <w lemma="3117">י֥וֹם</w>';
chapter0 += '    <w lemma="7243" n="0">רְבִיעִֽי</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '    <seg type="x-pe">פ</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.20">';
chapter0 += '    <w lemma="c/559">וַ/יֹּ֣אמֶר</w>';
chapter0 += '    <w lemma="430" n="1.2">אֱלֹהִ֔ים</w>';
chapter0 += '    <w lemma="8317">יִשְׁרְצ֣וּ</w>';
chapter0 += '    <w lemma="d/4325" n="1.1">הַ/מַּ֔יִם</w>';
chapter0 += '    <w lemma="8318" n="1.0">שֶׁ֖רֶץ</w>';
chapter0 += '    <w lemma="5315">נֶ֣פֶשׁ</w>';
chapter0 += '    <w lemma="2416 a" n="1">חַיָּ֑ה</w>';
chapter0 += '    <w lemma="c/5775" n="0.1.0">וְ/עוֹף֙</w>';
chapter0 += '    <w lemma="5774 a">יְעוֹפֵ֣ף</w>';
chapter0 += '    <w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="0.1">הָ/אָ֔רֶץ</w>';
chapter0 += '    <w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="6440" n="0.0">פְּנֵ֖י</w>';
chapter0 += '    <w lemma="7549">רְקִ֥יעַ</w>';
chapter0 += '    <w lemma="d/8064" n="0">הַ/שָּׁמָֽיִם</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.21">';
chapter0 += '    <w lemma="c/1254 a">וַ/יִּבְרָ֣א</w>';
chapter0 += '    <w lemma="430" n="1.1">אֱלֹהִ֔ים</w>';
chapter0 += '    <w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/8577 b" n="1.0">הַ/תַּנִּינִ֖ם</w>';
chapter0 += '    <w lemma="d/1419 a" n="1">הַ/גְּדֹלִ֑ים</w>';
chapter0 += '    <w lemma="c/853">וְ/אֵ֣ת</w>';
chapter0 += '    <w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="5315">נֶ֣פֶשׁ</w>';
chapter0 += '    <w lemma="d/2416 a" n="0.1.1.2">הַֽ/חַיָּ֣ה</w>';
chapter0 += '    <seg type="x-paseq">׀</seg>';
chapter0 += '    <w lemma="d/7430" n="0.1.1.1">הָֽ/רֹמֶ֡שֶׂת</w>';
chapter0 += '    <w lemma="834 a">אֲשֶׁר֩</w>';
chapter0 += '    <w lemma="8317">שָׁרְצ֨וּ</w>';
chapter0 += '    <w lemma="d/4325" n="0.1.1.0">הַ/מַּ֜יִם</w>';
chapter0 += '    <w lemma="l/4327" n="0.1.1">לְ/מִֽינֵ/הֶ֗ם</w>';
chapter0 += '    <w lemma="c/853">וְ/אֵ֨ת</w>';
chapter0 += '    <w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="5775">ע֤וֹף</w>';
chapter0 += '    <w lemma="3671" n="0.1.0">כָּנָף֙</w>';
chapter0 += '    <w lemma="l/4327" n="0.1">לְ/מִינֵ֔/הוּ</w>';
chapter0 += '    <w lemma="c/7200">וַ/יַּ֥רְא</w>';
chapter0 += '    <w lemma="430" n="0.0">אֱלֹהִ֖ים</w>';
chapter0 += '    <w lemma="3588 a">כִּי</w><seg type="x-maqqef">־</seg><w lemma="2896 a" n="0">טֽוֹב</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.22">';
chapter0 += '    <w lemma="c/1288">וַ/יְבָ֧רֶךְ</w>';
chapter0 += '    <w lemma="853" n="1.0.0">אֹתָ֛/ם</w>';
chapter0 += '    <w lemma="430" n="1.0">אֱלֹהִ֖ים</w>';
chapter0 += '    <w lemma="l/559" n="1">לֵ/אמֹ֑ר</w>';
chapter0 += '    <w lemma="6509">פְּר֣וּ</w>';
chapter0 += '    <w lemma="c/7235 a" n="0.1.1">וּ/רְב֗וּ</w>';
chapter0 += '    <w lemma="c/4390">וּ/מִלְא֤וּ</w>';
chapter0 += '    <w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/4325" n="0.1.0">הַ/מַּ֨יִם֙</w>';
chapter0 += '    <w lemma="b/3220" n="0.1">בַּ/יַּמִּ֔ים</w>';
chapter0 += '    <w lemma="c/d/5775" n="0.0">וְ/הָ/ע֖וֹף</w>';
chapter0 += '    <w lemma="7235 a">יִ֥רֶב</w>';
chapter0 += '    <w lemma="b/776" n="0">בָּ/אָֽרֶץ</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.23">';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="6153">עֶ֥רֶב</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="1242" n="0.0">בֹ֖קֶר</w>';
chapter0 += '    <w lemma="3117">י֥וֹם</w>';
chapter0 += '    <w lemma="2549" n="0">חֲמִישִֽׁי</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '    <seg type="x-pe">פ</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.24">';
chapter0 += '    <w lemma="c/559">וַ/יֹּ֣אמֶר</w>';
chapter0 += '    <w lemma="430" n="1.1.1">אֱלֹהִ֗ים</w>';
chapter0 += '    <w lemma="3318">תּוֹצֵ֨א</w>';
chapter0 += '    <w lemma="d/776" n="1.1.0.0">הָ/אָ֜רֶץ</w>';
chapter0 += '    <w lemma="5315">נֶ֤פֶשׁ</w>';
chapter0 += '    <w lemma="2416 a" n="1.1.0">חַיָּה֙</w>';
chapter0 += '    <w lemma="l/4327" n="1.1">לְ/מִינָ֔/הּ</w>';
chapter0 += '    <w lemma="929">בְּהֵמָ֥ה</w>';
chapter0 += '    <w lemma="c/7431" n="1.0.0">וָ/רֶ֛מֶשׂ</w>';
chapter0 += '    <w lemma="c/2416 c">וְ/חַֽיְתוֹ</w><seg type="x-maqqef">־</seg><w lemma="776" n="1.0">אֶ֖רֶץ</w>';
chapter0 += '    <w lemma="l/4327" n="1">לְ/מִינָ֑/הּ</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="3651 c" n="0">כֵֽן</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.25">';
chapter0 += '    <w lemma="c/6213 a">וַ/יַּ֣עַשׂ</w>';
chapter0 += '    <w lemma="430">אֱלֹהִים֩</w>';
chapter0 += '    <w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="2416 c">חַיַּ֨ת</w>';
chapter0 += '    <w lemma="d/776" n="1.1.1.0">הָ/אָ֜רֶץ</w>';
chapter0 += '    <w lemma="l/4327" n="1.1.1">לְ/מִינָ֗/הּ</w>';
chapter0 += '    <w lemma="c/853">וְ/אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/929" n="1.1.0">הַ/בְּהֵמָה֙</w>';
chapter0 += '    <w lemma="l/4327" n="1.1">לְ/מִינָ֔/הּ</w>';
chapter0 += '    <w lemma="c/853" n="1.0.0">וְ/אֵ֛ת</w>';
chapter0 += '    <w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="7431">רֶ֥מֶשׂ</w>';
chapter0 += '    <w lemma="d/127" n="1.0">הָֽ/אֲדָמָ֖ה</w>';
chapter0 += '    <w lemma="l/4327" n="1">לְ/מִינֵ֑/הוּ</w>';
chapter0 += '    <w lemma="c/7200">וַ/יַּ֥רְא</w>';
chapter0 += '    <w lemma="430" n="0.0">אֱלֹהִ֖ים</w>';
chapter0 += '    <w lemma="3588 a">כִּי</w><seg type="x-maqqef">־</seg><w lemma="2896 a" n="0">טֽוֹב</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.26">';
chapter0 += '    <w lemma="c/559">וַ/יֹּ֣אמֶר</w>';
chapter0 += '    <w lemma="430" n="1.1">אֱלֹהִ֔ים</w>';
chapter0 += '    <w lemma="6213 a">נַֽעֲשֶׂ֥ה</w>';
chapter0 += '    <w lemma="120" n="1.0.0">אָדָ֛ם</w>';
chapter0 += '    <w lemma="b/6754" n="1.0">בְּ/צַלְמֵ֖/נוּ</w>';
chapter0 += '    <w lemma="k/1823" n="1">כִּ/דְמוּתֵ֑/נוּ</w>';
chapter0 += '    <w lemma="c/7287 a">וְ/יִרְדּוּ֩</w>';
chapter0 += '    <w lemma="b/1710">בִ/דְגַ֨ת</w>';
chapter0 += '    <w lemma="d/3220" n="0.1.1.0">הַ/יָּ֜ם</w>';
chapter0 += '    <w lemma="c/b/5775">וּ/בְ/ע֣וֹף</w>';
chapter0 += '    <w lemma="d/8064" n="0.1.1">הַ/שָּׁמַ֗יִם</w>';
chapter0 += '    <w lemma="c/b/929" n="0.1.0">וּ/בַ/בְּהֵמָה֙</w>';
chapter0 += '    <w lemma="c/b/3605">וּ/בְ/כָל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="0.1">הָ/אָ֔רֶץ</w>';
chapter0 += '    <w lemma="c/b/3605">וּ/בְ/כָל</w><seg type="x-maqqef">־</seg><w lemma="d/7431" n="0.0">הָ/רֶ֖מֶשׂ</w>';
chapter0 += '    <w lemma="d/7430">הָֽ/רֹמֵ֥שׂ</w>';
chapter0 += '    <w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="0">הָ/אָֽרֶץ</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.27">';
chapter0 += '    <w lemma="c/1254 a">וַ/יִּבְרָ֨א</w>';
chapter0 += '    <w lemma="430">אֱלֹהִ֤ים</w>';
chapter0 += '    <seg type="x-paseq">׀</seg>';
chapter0 += '    <w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/120" n="1.1.0">הָֽ/אָדָם֙</w>';
chapter0 += '    <w lemma="b/6754" n="1.1">בְּ/צַלְמ֔/וֹ</w>';
chapter0 += '    <w lemma="b/6754">בְּ/צֶ֥לֶם</w>';
chapter0 += '    <w lemma="430" n="1.0">אֱלֹהִ֖ים</w>';
chapter0 += '    <w lemma="1254 a">בָּרָ֣א</w>';
chapter0 += '    <w lemma="853" n="1">אֹת֑/וֹ</w>';
chapter0 += '    <w lemma="2145">זָכָ֥ר</w>';
chapter0 += '    <w lemma="c/5347" n="0.0">וּ/נְקֵבָ֖ה</w>';
chapter0 += '    <w lemma="1254 a">בָּרָ֥א</w>';
chapter0 += '    <w lemma="853" n="0">אֹתָֽ/ם</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.28">';
chapter0 += '    <w lemma="c/1288">וַ/יְבָ֣רֶךְ</w>';
chapter0 += '    <w lemma="853" n="1.1.0">אֹתָ/ם֮</w>';
chapter0 += '    <w lemma="430" n="1.1">אֱלֹהִים֒</w>';
chapter0 += '    <w lemma="c/559">וַ/יֹּ֨אמֶר</w>';
chapter0 += '    <w lemma="l" n="1.0.1.0">לָ/הֶ֜ם</w>';
chapter0 += '    <w lemma="430" n="1.0.1">אֱלֹהִ֗ים</w>';
chapter0 += '    <w lemma="6509">פְּר֥וּ</w>';
chapter0 += '    <w lemma="c/7235 a" n="1.0.0">וּ/רְב֛וּ</w>';
chapter0 += '    <w lemma="c/4390">וּ/מִלְא֥וּ</w>';
chapter0 += '    <w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="1.0">הָ/אָ֖רֶץ</w>';
chapter0 += '    <w lemma="c/3533" n="1">וְ/כִבְשֻׁ֑/הָ</w>';
chapter0 += '    <w lemma="c/7287 a" n="0.1.0.0">וּ/רְד֞וּ</w>';
chapter0 += '    <w lemma="b/1710">בִּ/דְגַ֤ת</w>';
chapter0 += '    <w lemma="d/3220" n="0.1.0">הַ/יָּם֙</w>';
chapter0 += '    <w lemma="c/b/5775">וּ/בְ/ע֣וֹף</w>';
chapter0 += '    <w lemma="d/8064" n="0.1">הַ/שָּׁמַ֔יִם</w>';
chapter0 += '    <w lemma="c/b/3605">וּ/בְ/כָל</w><seg type="x-maqqef">־</seg><w lemma="2416 a" n="0.0">חַיָּ֖ה</w>';
chapter0 += '    <w lemma="d/7430">הָֽ/רֹמֶ֥שֶׂת</w>';
chapter0 += '    <w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="0">הָ/אָֽרֶץ</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.29">';
chapter0 += '    <w lemma="c/559">וַ/יֹּ֣אמֶר</w>';
chapter0 += '    <w lemma="430" n="1.1.2">אֱלֹהִ֗ים</w>';
chapter0 += '    <w lemma="2009">הִנֵּה֩</w>';
chapter0 += '    <w lemma="5414">נָתַ֨תִּי</w>';
chapter0 += '    <w lemma="l" n="1.1.1.1">לָ/כֶ֜ם</w>';
chapter0 += '    <w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="6212" n="1.1.1.0">עֵ֣שֶׂב</w>';
chapter0 += '    <seg type="x-paseq">׀</seg>';
chapter0 += '    <w lemma="2232">זֹרֵ֣עַ</w>';
chapter0 += '    <w lemma="2233" n="1.1.1">זֶ֗רַע</w>';
chapter0 += '    <w lemma="834 a" n="1.1.0">אֲשֶׁר֙</w>';
chapter0 += '    <w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="6440">פְּנֵ֣י</w>';
chapter0 += '    <w lemma="3605">כָל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="1.1">הָ/אָ֔רֶץ</w>';
chapter0 += '    <w lemma="c/853">וְ/אֶת</w><seg type="x-maqqef">־</seg><w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="d/6086" n="1.0.0">הָ/עֵ֛ץ</w>';
chapter0 += '    <w lemma="834 a">אֲשֶׁר</w><seg type="x-maqqef">־</seg><w lemma="b">בּ֥/וֹ</w>';
chapter0 += '    <w lemma="6529">פְרִי</w><seg type="x-maqqef">־</seg><w lemma="6086" n="1.0">עֵ֖ץ</w>';
chapter0 += '    <w lemma="2232">זֹרֵ֣עַ</w>';
chapter0 += '    <w lemma="2233" n="1">זָ֑רַע</w>';
chapter0 += '    <w lemma="l">לָ/כֶ֥ם</w>';
chapter0 += '    <w lemma="1961" n="0.0">יִֽהְיֶ֖ה</w>';
chapter0 += '    <w lemma="l/402" n="0">לְ/אָכְלָֽה</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.30">';
chapter0 += '    <w lemma="c/l/3605">וּֽ/לְ/כָל</w><seg type="x-maqqef">־</seg><w lemma="2416 c">חַיַּ֣ת</w>';
chapter0 += '    <w lemma="d/776" n="1.1.1.2">הָ֠/אָרֶץ</w>';
chapter0 += '    <w lemma="c/l/3605">וּ/לְ/כָל</w><seg type="x-maqqef">־</seg><w lemma="5775">ע֨וֹף</w>';
chapter0 += '    <w lemma="d/8064" n="1.1.1.1">הַ/שָּׁמַ֜יִם</w>';
chapter0 += '    <w lemma="c/l/3605" n="1.1.1.0">וּ/לְ/כֹ֣ל</w>';
chapter0 += '    <seg type="x-paseq">׀</seg>';
chapter0 += '    <w lemma="7430">רוֹמֵ֣שׂ</w>';
chapter0 += '    <w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="1.1.1">הָ/אָ֗רֶץ</w>';
chapter0 += '    <w lemma="834 a">אֲשֶׁר</w><seg type="x-maqqef">־</seg><w lemma="b" n="1.1.0">בּ/וֹ֙</w>';
chapter0 += '    <w lemma="5315">נֶ֣פֶשׁ</w>';
chapter0 += '    <w lemma="2416 a" n="1.1">חַיָּ֔ה</w>';
chapter0 += '    <w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="3418">יֶ֥רֶק</w>';
chapter0 += '    <w lemma="6212" n="1.0">עֵ֖שֶׂב</w>';
chapter0 += '    <w lemma="l/402" n="1">לְ/אָכְלָ֑ה</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="3651 c" n="0">כֵֽן</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '  </verse>';
chapter0 += '  <verse osisID="Gen.1.31">';
chapter0 += '    <w lemma="c/7200">וַ/יַּ֤רְא</w>';
chapter0 += '    <w lemma="430" n="1.1.0">אֱלֹהִים֙</w>';
chapter0 += '    <w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="834 a">אֲשֶׁ֣ר</w>';
chapter0 += '    <w lemma="6213 a" n="1.1">עָשָׂ֔ה</w>';
chapter0 += '    <w lemma="c/2009">וְ/הִנֵּה</w><seg type="x-maqqef">־</seg><w lemma="2896 a" n="1.0">ט֖וֹב</w>';
chapter0 += '    <w lemma="3966" n="1">מְאֹ֑ד</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="6153">עֶ֥רֶב</w>';
chapter0 += '    <w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="1242" n="0.0">בֹ֖קֶר</w>';
chapter0 += '    <w lemma="3117">י֥וֹם</w>';
chapter0 += '    <w lemma="d/8345" n="0">הַ/שִּׁשִּֽׁי</w><seg type="x-sof-pasuq">׃</seg>';
chapter0 += '    <seg type="x-pe">פ</seg>';
chapter0 += '  </verse>';
chapter0 += '</chapter>';