chapter2 = '<?xml version="1.0" encoding="UTF-8"?>';
chapter2 += '<chapter osisID="Gen.32">';
chapter2 += '	<verse osisID="Gen.32.1">';
chapter2 += '		<note>KJV:Gen.31.55</note>';
chapter2 += '		<w lemma="c/7925">וַ/יַּשְׁכֵּ֨ם</w>';
chapter2 += '		<w lemma="3837 a" n="1.0.1.0">לָבָ֜ן</w>';
chapter2 += '		<w lemma="b/1242" n="1.0.1">בַּ/בֹּ֗קֶר</w>';
chapter2 += '		<w lemma="c/5401 a">וַ/יְנַשֵּׁ֧ק</w>';
chapter2 += '		<w lemma="l/1121 a" n="1.0.0">לְ/בָנָ֛י/ו</w>';
chapter2 += '		<w lemma="c/l/1323" n="1.0">וְ/לִ/בְנוֹתָ֖י/ו</w>';
chapter2 += '		<w lemma="c/1288">וַ/יְבָ֣רֶךְ</w>';
chapter2 += '		<w lemma="853" n="1">אֶתְ/הֶ֑ם</w>';
chapter2 += '		<w lemma="c/3212" n="0.0.0">וַ/יֵּ֛לֶךְ</w>';
chapter2 += '		<w lemma="c/7725">וַ/יָּ֥שָׁב</w>';
chapter2 += '		<w lemma="3837 a" n="0.0">לָבָ֖ן</w>';
chapter2 += '		<w lemma="l/4725" n="0">לִ/מְקֹמֽ/וֹ</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.2">';
chapter2 += '		<note>KJV:Gen.32.1</note>';
chapter2 += '		<w lemma="c/3290" n="1.0">וְ/יַעֲקֹ֖ב</w>';
chapter2 += '		<w lemma="1980">הָלַ֣ךְ</w>';
chapter2 += '		<w lemma="l/1870" n="1">לְ/דַרְכּ֑/וֹ</w>';
chapter2 += '		<w lemma="c/6293">וַ/יִּפְגְּעוּ</w><seg type="x-maqqef">־</seg><w lemma="b" n="0.0">ב֖/וֹ</w>';
chapter2 += '		<w lemma="4397">מַלְאֲכֵ֥י</w>';
chapter2 += '		<w lemma="430" n="0">אֱלֹהִֽים</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.3">';
chapter2 += '		<note>KJV:Gen.32.2</note>';
chapter2 += '		<w lemma="c/559">וַ/יֹּ֤אמֶר</w>';
chapter2 += '		<w lemma="3290" n="1.1.0">יַעֲקֹב֙</w>';
chapter2 += '		<w lemma="k/834 d">כַּ/אֲשֶׁ֣ר</w>';
chapter2 += '		<w lemma="7200" n="1.1">רָאָ֔/ם</w>';
chapter2 += '		<w lemma="4264">מַחֲנֵ֥ה</w>';
chapter2 += '		<w lemma="430" n="1.0">אֱלֹהִ֖ים</w>';
chapter2 += '		<w lemma="2088" n="1">זֶ֑ה</w>';
chapter2 += '		<w lemma="c/7121" n="0.0.0">וַ/יִּקְרָ֛א</w>';
chapter2 += '		<w lemma="8034">שֵֽׁם</w><seg type="x-maqqef">־</seg><w lemma="d/4725">הַ/מָּק֥וֹם</w>';
chapter2 += '		<w lemma="d/1931" n="0.0">הַ/ה֖וּא</w>';
chapter2 += '		<w lemma="4266" n="0">מַֽחֲנָֽיִם</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '		<seg type="x-pe">פ</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.4">';
chapter2 += '		<note>KJV:Gen.32.3</note>';
chapter2 += '		<w lemma="c/7971">וַ/יִּשְׁלַ֨ח</w>';
chapter2 += '		<w lemma="3290">יַעֲקֹ֤ב</w>';
chapter2 += '		<w lemma="4397" n="1.1.0">מַלְאָכִים֙</w>';
chapter2 += '		<w lemma="l/6440" n="1.1">לְ/פָנָ֔י/ו</w>';
chapter2 += '		<w lemma="413">אֶל</w><seg type="x-maqqef">־</seg><w lemma="6215" n="1.0">עֵשָׂ֖ו</w>';
chapter2 += '		<w lemma="251" n="1">אָחִ֑י/ו</w>';
chapter2 += '		<w lemma="776">אַ֥רְצָ/ה</w>';
chapter2 += '		<w lemma="8165 a" n="0.0">שֵׂעִ֖יר</w>';
chapter2 += '		<w lemma="7704 b">שְׂדֵ֥ה</w>';
chapter2 += '		<w lemma="123" n="0">אֱדֽוֹם</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.5">';
chapter2 += '		<note>KJV:Gen.32.4</note>';
chapter2 += '		<w lemma="c/6680">וַ/יְצַ֤ו</w>';
chapter2 += '		<w lemma="853" n="1.2.0">אֹתָ/ם֙</w>';
chapter2 += '		<w lemma="l/559" n="1.2">לֵ/אמֹ֔ר</w>';
chapter2 += '		<w lemma="3541">כֹּ֣ה</w>';
chapter2 += '		<w lemma="559" n="1.1">תֹאמְר֔וּ/ן</w>';
chapter2 += '		<w lemma="l/113" n="1.0">לַֽ/אדֹנִ֖/י</w>';
chapter2 += '		<w lemma="l/6215" n="1">לְ/עֵשָׂ֑ו</w>';
chapter2 += '		<w lemma="3541">כֹּ֤ה</w>';
chapter2 += '		<w lemma="559" n="0.2.0">אָמַר֙</w>';
chapter2 += '		<w lemma="5650">עַבְדְּ/ךָ֣</w>';
chapter2 += '		<w lemma="3290" n="0.2">יַעֲקֹ֔ב</w>';
chapter2 += '		<w lemma="5973 a">עִם</w><seg type="x-maqqef">־</seg><w lemma="3837 a">לָבָ֣ן</w>';
chapter2 += '		<w lemma="1481 a" n="0.1">גַּ֔רְתִּי</w>';
chapter2 += '		<w lemma="c/309" n="0.0">וָ/אֵחַ֖ר</w>';
chapter2 += '		<w lemma="5704">עַד</w><seg type="x-maqqef">־</seg><w lemma="6258" n="0">עָֽתָּה</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.6">';
chapter2 += '		<note>KJV:Gen.32.5</note>';
chapter2 += '		<w lemma="c/1961">וַֽ/יְהִי</w><seg type="x-maqqef">־</seg><w lemma="l" n="1.1.0">לִ/י֙</w>';
chapter2 += '		<w lemma="7794">שׁ֣וֹר</w>';
chapter2 += '		<w lemma="c/2543" n="1.1">וַ/חֲמ֔וֹר</w>';
chapter2 += '		<w lemma="6629" n="1.0">צֹ֖אן</w>';
chapter2 += '		<w lemma="c/5650">וְ/עֶ֣בֶד</w>';
chapter2 += '		<w lemma="c/8198" n="1">וְ/שִׁפְחָ֑ה</w>';
chapter2 += '		<w lemma="c/7971" n="0.1.0">וָֽ/אֶשְׁלְחָ/ה֙</w>';
chapter2 += '		<w lemma="l/5046">לְ/הַגִּ֣יד</w>';
chapter2 += '		<w lemma="l/113" n="0.1">לַֽ/אדֹנִ֔/י</w>';
chapter2 += '		<w lemma="l/4672">לִ/מְצֹא</w><seg type="x-maqqef">־</seg><w lemma="2580" n="0.0">חֵ֖ן</w>';
chapter2 += '		<w lemma="b/5869 a" n="0">בְּ/עֵינֶֽי/ךָ</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.7">';
chapter2 += '		<note>KJV:Gen.32.6</note>';
chapter2 += '		<w lemma="c/7725" n="1.1.0">וַ/יָּשֻׁ֙בוּ֙</w>';
chapter2 += '		<w lemma="d/4397" n="1.1">הַ/מַּלְאָכִ֔ים</w>';
chapter2 += '		<w lemma="413">אֶֽל</w><seg type="x-maqqef">־</seg><w lemma="3290" n="1.0">יַעֲקֹ֖ב</w>';
chapter2 += '		<w lemma="l/559" n="1">לֵ/אמֹ֑ר</w>';
chapter2 += '		<w lemma="935">בָּ֤אנוּ</w>';
chapter2 += '		<w lemma="413">אֶל</w><seg type="x-maqqef">־</seg><w lemma="251" n="0.2.0">אָחִ֙י/ךָ֙</w>';
chapter2 += '		<w lemma="413">אֶל</w><seg type="x-maqqef">־</seg><w lemma="6215" n="0.2">עֵשָׂ֔ו</w>';
chapter2 += '		<w lemma="c/1571" n="0.1.0">וְ/גַם֙</w>';
chapter2 += '		<w lemma="1980">הֹלֵ֣ךְ</w>';
chapter2 += '		<w lemma="l/7125" n="0.1">לִ/קְרָֽאתְ/ךָ֔</w>';
chapter2 += '		<w lemma="c/702">וְ/אַרְבַּע</w><seg type="x-maqqef">־</seg><w lemma="3967">מֵא֥וֹת</w>';
chapter2 += '		<w lemma="376" n="0.0">אִ֖ישׁ</w>';
chapter2 += '		<w lemma="5973 a" n="0">עִמּֽ/וֹ</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.8">';
chapter2 += '		<note>KJV:Gen.32.7</note>';
chapter2 += '		<w lemma="c/3372">וַ/יִּירָ֧א</w>';
chapter2 += '		<w lemma="3290" n="1.0.0">יַעֲקֹ֛ב</w>';
chapter2 += '		<w lemma="3966" n="1.0">מְאֹ֖ד</w>';
chapter2 += '		<w lemma="c/3334">וַ/יֵּ֣צֶר</w>';
chapter2 += '		<w lemma="l" n="1">ל֑/וֹ</w>';
chapter2 += '		<w lemma="c/2673" n="0.0.1.0">וַ/יַּ֜חַץ</w>';
chapter2 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/5971 a">הָ/עָ֣ם</w>';
chapter2 += '		<w lemma="834 a">אֲשֶׁר</w><seg type="x-maqqef">־</seg><w lemma="854" n="0.0.1">אִתּ֗/וֹ</w>';
chapter2 += '		<w lemma="c/853">וְ/אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/6629">הַ/צֹּ֧אן</w>';
chapter2 += '		<w lemma="c/853">וְ/אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/1241" n="0.0.0">הַ/בָּקָ֛ר</w>';
chapter2 += '		<w lemma="c/d/1581" n="0.0">וְ/הַ/גְּמַלִּ֖ים</w>';
chapter2 += '		<w lemma="l/8147">לִ/שְׁנֵ֥י</w>';
chapter2 += '		<w lemma="4264" n="0">מַחֲנֽוֹת</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.9">';
chapter2 += '		<note>KJV:Gen.32.8</note>';
chapter2 += '		<w lemma="c/559" n="1.1">וַ/יֹּ֕אמֶר</w>';
chapter2 += '		<w lemma="518 a">אִם</w><seg type="x-maqqef">־</seg><w lemma="935">יָב֥וֹא</w>';
chapter2 += '		<w lemma="6215" n="1.0.0">עֵשָׂ֛ו</w>';
chapter2 += '		<w lemma="413">אֶל</w><seg type="x-maqqef">־</seg><w lemma="d/4264">הַ/מַּחֲנֶ֥ה</w>';
chapter2 += '		<w lemma="d/259" n="1.0">הָ/אַחַ֖ת</w>';
chapter2 += '		<w lemma="c/5221" n="1">וְ/הִכָּ֑/הוּ</w>';
chapter2 += '		<w lemma="c/1961" n="0.0.0">וְ/הָיָ֛ה</w>';
chapter2 += '		<w lemma="d/4264">הַ/מַּחֲנֶ֥ה</w>';
chapter2 += '		<w lemma="d/7604" n="0.0">הַ/נִּשְׁאָ֖ר</w>';
chapter2 += '		<w lemma="l/6413" n="0">לִ/פְלֵיטָֽה</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.10">';
chapter2 += '		<note>KJV:Gen.32.9</note>';
chapter2 += '		<w lemma="c/559" n="1.2.0">וַ/יֹּאמֶר֮</w>';
chapter2 += '		<w lemma="3290" n="1.2">יַעֲקֹב֒</w>';
chapter2 += '		<w lemma="430" n="1.1.0">אֱלֹהֵי֙</w>';
chapter2 += '		<w lemma="1">אָבִ֣/י</w>';
chapter2 += '		<w lemma="85" n="1.1">אַבְרָהָ֔ם</w>';
chapter2 += '		<w lemma="c/430" n="1.0">וֵ/אלֹהֵ֖י</w>';
chapter2 += '		<w lemma="1">אָבִ֣/י</w>';
chapter2 += '		<w lemma="3327" n="1">יִצְחָ֑ק</w>';
chapter2 += '		<w lemma="3068" n="0.0.1.0">יְהוָ֞ה</w>';
chapter2 += '		<w lemma="d/559">הָ/אֹמֵ֣ר</w>';
chapter2 += '		<w lemma="413" n="0.0.1">אֵלַ֗/י</w>';
chapter2 += '		<w lemma="7725">שׁ֧וּב</w>';
chapter2 += '		<w lemma="l/776" n="0.0.0">לְ/אַרְצְ/ךָ֛</w>';
chapter2 += '		<w lemma="c/l/4138" n="0.0">וּ/לְ/מוֹלַדְתְּ/ךָ֖</w>';
chapter2 += '		<w lemma="c/3190">וְ/אֵיטִ֥יבָה</w>';
chapter2 += '		<w lemma="5973 a" n="0">עִמָּֽ/ךְ</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.11">';
chapter2 += '		<note>KJV:Gen.32.10</note>';
chapter2 += '		<w lemma="6994" n="1.1.0.0">קָטֹ֜נְתִּי</w>';
chapter2 += '		<w lemma="m/3605">מִ/כֹּ֤ל</w>';
chapter2 += '		<w lemma="d/2617 a" n="1.1.0">הַ/חֲסָדִים֙</w>';
chapter2 += '		<w lemma="c/m/3605">וּ/מִ/כָּל</w><seg type="x-maqqef">־</seg><w lemma="d/571" n="1.1">הָ֣/אֱמֶ֔ת</w>';
chapter2 += '		<w lemma="834 a">אֲשֶׁ֥ר</w>';
chapter2 += '		<w lemma="6213 a" n="1.0">עָשִׂ֖יתָ</w>';
chapter2 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="5650" n="1">עַבְדֶּ֑/ךָ</w>';
chapter2 += '		<w lemma="3588 a">כִּ֣י</w>';
chapter2 += '		<w lemma="b/4731" n="0.1.1">בְ/מַקְלִ֗/י</w>';
chapter2 += '		<w lemma="5674 a" n="0.1.0">עָבַ֙רְתִּי֙</w>';
chapter2 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/3383">הַ/יַּרְדֵּ֣ן</w>';
chapter2 += '		<w lemma="d/2088" n="0.1">הַ/זֶּ֔ה</w>';
chapter2 += '		<w lemma="c/6258">וְ/עַתָּ֥ה</w>';
chapter2 += '		<w lemma="1961" n="0.0">הָיִ֖יתִי</w>';
chapter2 += '		<w lemma="l/8147">לִ/שְׁנֵ֥י</w>';
chapter2 += '		<w lemma="4264" n="0">מַחֲנֽוֹת</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.12">';
chapter2 += '		<note>KJV:Gen.32.11</note>';
chapter2 += '		<w lemma="5337">הַצִּילֵ֥/נִי</w>';
chapter2 += '		<w lemma="4994" n="1.0.0">נָ֛א</w>';
chapter2 += '		<w lemma="m/3027">מִ/יַּ֥ד</w>';
chapter2 += '		<w lemma="251" n="1.0">אָחִ֖/י</w>';
chapter2 += '		<w lemma="m/3027">מִ/יַּ֣ד</w>';
chapter2 += '		<w lemma="6215" n="1">עֵשָׂ֑ו</w>';
chapter2 += '		<w lemma="3588 a">כִּֽי</w><seg type="x-maqqef">־</seg><w lemma="3373">יָרֵ֤א</w>';
chapter2 += '		<w lemma="595" n="0.2.0">אָנֹכִי֙</w>';
chapter2 += '		<w lemma="853" n="0.2">אֹת֔/וֹ</w>';
chapter2 += '		<w lemma="6435">פֶּן</w><seg type="x-maqqef">־</seg><w lemma="935">יָב֣וֹא</w>';
chapter2 += '		<w lemma="c/5221" n="0.1">וְ/הִכַּ֔/נִי</w>';
chapter2 += '		<w lemma="517" n="0.0">אֵ֖ם</w>';
chapter2 += '		<w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="1121 a" n="0">בָּנִֽים</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.13">';
chapter2 += '		<note>KJV:Gen.32.12</note>';
chapter2 += '		<w lemma="c/859 a">וְ/אַתָּ֣ה</w>';
chapter2 += '		<w lemma="559" n="1.1">אָמַ֔רְתָּ</w>';
chapter2 += '		<w lemma="3190">הֵיטֵ֥ב</w>';
chapter2 += '		<w lemma="3190" n="1.0">אֵיטִ֖יב</w>';
chapter2 += '		<w lemma="5973 a" n="1">עִמָּ֑/ךְ</w>';
chapter2 += '		<w lemma="c/7760 a">וְ/שַׂמְתִּ֤י</w>';
chapter2 += '		<w lemma="853">אֶֽת</w><seg type="x-maqqef">־</seg><w lemma="2233" n="0.1.0">זַרְעֲ/ךָ֙</w>';
chapter2 += '		<w lemma="k/2344">כְּ/ח֣וֹל</w>';
chapter2 += '		<w lemma="d/3220" n="0.1">הַ/יָּ֔ם</w>';
chapter2 += '		<w lemma="834 a">אֲשֶׁ֥ר</w>';
chapter2 += '		<w lemma="3808">לֹא</w><seg type="x-maqqef">־</seg><w lemma="5608 a" n="0.0">יִסָּפֵ֖ר</w>';
chapter2 += '		<w lemma="m/7230" n="0">מֵ/רֹֽב</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.14">';
chapter2 += '		<note>KJV:Gen.32.13</note>';
chapter2 += '		<w lemma="c/3885 a">וַ/יָּ֥לֶן</w>';
chapter2 += '		<w lemma="8033" n="1.0">שָׁ֖ם</w>';
chapter2 += '		<w lemma="b/3915">בַּ/לַּ֣יְלָה</w>';
chapter2 += '		<w lemma="d/1931" n="1">הַ/ה֑וּא</w>';
chapter2 += '		<w lemma="c/3947" n="0.0.0.0">וַ/יִּקַּ֞ח</w>';
chapter2 += '		<w lemma="4480 a">מִן</w><seg type="x-maqqef">־</seg><w lemma="d/935">הַ/בָּ֧א</w>';
chapter2 += '		<w lemma="b/3027" n="0.0.0">בְ/יָד֛/וֹ</w>';
chapter2 += '		<w lemma="4503" n="0.0">מִנְחָ֖ה</w>';
chapter2 += '		<w lemma="l/6215">לְ/עֵשָׂ֥ו</w>';
chapter2 += '		<w lemma="251" n="0">אָחִֽי/ו</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.15">';
chapter2 += '		<note>KJV:Gen.32.14</note>';
chapter2 += '		<w lemma="5795">עִזִּ֣ים</w>';
chapter2 += '		<w lemma="3967" n="1.1">מָאתַ֔יִם</w>';
chapter2 += '		<w lemma="c/8495" n="1.0">וּ/תְיָשִׁ֖ים</w>';
chapter2 += '		<w lemma="6242" n="1">עֶשְׂרִ֑ים</w>';
chapter2 += '		<w lemma="7353">רְחֵלִ֥ים</w>';
chapter2 += '		<w lemma="3967" n="0.0">מָאתַ֖יִם</w>';
chapter2 += '		<w lemma="c/352 a">וְ/אֵילִ֥ים</w>';
chapter2 += '		<w lemma="6242" n="0">עֶשְׂרִֽים</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.16">';
chapter2 += '		<note>KJV:Gen.32.15</note>';
chapter2 += '		<w lemma="1581">גְּמַלִּ֧ים</w>';
chapter2 += '		<w lemma="3243" n="1.0.0">מֵינִיק֛וֹת</w>';
chapter2 += '		<w lemma="c/1121 a" n="1.0">וּ/בְנֵי/הֶ֖ם</w>';
chapter2 += '		<w lemma="7970" n="1">שְׁלֹשִׁ֑ים</w>';
chapter2 += '		<w lemma="6510">פָּר֤וֹת</w>';
chapter2 += '		<w lemma="705" n="0.2.0">אַרְבָּעִים֙</w>';
chapter2 += '		<w lemma="c/6499">וּ/פָרִ֣ים</w>';
chapter2 += '		<w lemma="6235" n="0.2">עֲשָׂרָ֔ה</w>';
chapter2 += '		<w lemma="860">אֲתֹנֹ֣ת</w>';
chapter2 += '		<w lemma="6242" n="0.1">עֶשְׂרִ֔ים</w>';
chapter2 += '		<w lemma="c/5895" n="0.0">וַ/עְיָרִ֖ם</w>';
chapter2 += '		<note n="1">BHS has been faithful to the Leningrad Codex where there might be a question of the validity of the form and we keep the same form as BHS. </note>';
chapter2 += '		<w lemma="6235" n="0">עֲשָׂרָֽה</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.17">';
chapter2 += '		<note>KJV:Gen.32.16</note>';
chapter2 += '		<w lemma="c/5414" n="1.1.0">וַ/יִּתֵּן֙</w>';
chapter2 += '		<w lemma="b/3027">בְּ/יַד</w><seg type="x-maqqef">־</seg><w lemma="5650" n="1.1">עֲבָדָ֔י/ו</w>';
chapter2 += '		<w lemma="5739">עֵ֥דֶר</w>';
chapter2 += '		<w lemma="5739" n="1.0">עֵ֖דֶר</w>';
chapter2 += '		<w lemma="l/905" n="1">לְ/בַדּ֑/וֹ</w>';
chapter2 += '		<w lemma="c/559">וַ֤/יֹּאמֶר</w>';
chapter2 += '		<w lemma="413">אֶל</w><seg type="x-maqqef">־</seg><w lemma="5650" n="0.2.0">עֲבָדָי/ו֙</w>';
chapter2 += '		<w lemma="5674 a">עִבְר֣וּ</w>';
chapter2 += '		<w lemma="l/6440" n="0.2">לְ/פָנַ֔/י</w>';
chapter2 += '		<w lemma="c/7305">וְ/רֶ֣וַח</w>';
chapter2 += '		<w lemma="7760 a" n="0.1">תָּשִׂ֔ימוּ</w>';
chapter2 += '		<w lemma="996">בֵּ֥ין</w>';
chapter2 += '		<w lemma="5739" n="0.0">עֵ֖דֶר</w>';
chapter2 += '		<w lemma="c/996">וּ/בֵ֥ין</w>';
chapter2 += '		<w lemma="5739" n="0">עֵֽדֶר</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.18">';
chapter2 += '		<note>KJV:Gen.32.17</note>';
chapter2 += '		<w lemma="c/6680">וַ/יְצַ֥ו</w>';
chapter2 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/7223" n="1.0">הָ/רִאשׁ֖וֹן</w>';
chapter2 += '		<w lemma="l/559" n="1">לֵ/אמֹ֑ר</w>';
chapter2 += '		<w lemma="3588 a">כִּ֣י</w>';
chapter2 += '		<w lemma="6298" n="0.2.1.0">יִֽפְגָּשְׁ/ךָ֞</w>';
chapter2 += '		<note n="1">BHS has been faithful to the Leningrad Codex where there might be a question of the validity of the form and we keep the same form as BHS. </note>';
chapter2 += '		<w lemma="6215">עֵשָׂ֣ו</w>';
chapter2 += '		<w lemma="251" n="0.2.1">אָחִ֗/י</w>';
chapter2 += '		<w lemma="c/7592" n="0.2.0">וִ/שְׁאֵֽלְ/ךָ֙</w>';
chapter2 += '		<note n="1">BHS has been faithful to the Leningrad Codex where there might be a question of the validity of the form and we keep the same form as BHS. </note>';
chapter2 += '		<w lemma="l/559" n="0.2">לֵ/אמֹ֔ר</w>';
chapter2 += '		<w lemma="l/4310">לְ/מִי</w><seg type="x-maqqef">־</seg><w lemma="859 a" n="0.1.0">אַ֙תָּה֙</w>';
chapter2 += '		<w lemma="c/575">וְ/אָ֣נָה</w>';
chapter2 += '		<w lemma="3212" n="0.1">תֵלֵ֔ךְ</w>';
chapter2 += '		<w lemma="c/l/4310" n="0.0">וּ/לְ/מִ֖י</w>';
chapter2 += '		<w lemma="428">אֵ֥לֶּה</w>';
chapter2 += '		<w lemma="l/6440" n="0">לְ/פָנֶֽי/ךָ</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.19">';
chapter2 += '		<note>KJV:Gen.32.18</note>';
chapter2 += '		<w lemma="c/559" n="1.2.0">וְ/אָֽמַרְתָּ֙</w>';
chapter2 += '		<w lemma="l/5650">לְ/עַבְדְּ/ךָ֣</w>';
chapter2 += '		<w lemma="l/3290" n="1.2">לְ/יַעֲקֹ֔ב</w>';
chapter2 += '		<w lemma="4503">מִנְחָ֥ה</w>';
chapter2 += '		<w lemma="1931" n="1.1.0">הִוא֙</w>';
chapter2 += '		<w lemma="7971" n="1.1">שְׁלוּחָ֔ה</w>';
chapter2 += '		<w lemma="l/113" n="1.0">לַֽ/אדֹנִ֖/י</w>';
chapter2 += '		<w lemma="l/6215" n="1">לְ/עֵשָׂ֑ו</w>';
chapter2 += '		<w lemma="c/2009">וְ/הִנֵּ֥ה</w>';
chapter2 += '		<w lemma="1571">גַם</w><seg type="x-maqqef">־</seg><w lemma="1931" n="0.0">ה֖וּא</w>';
chapter2 += '		<w lemma="310 a" n="0">אַחֲרֵֽי/נוּ</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.20">';
chapter2 += '		<note>KJV:Gen.32.19</note>';
chapter2 += '		<w lemma="c/6680" n="1.2.1.0">וַ/יְצַ֞ו</w>';
chapter2 += '		<w lemma="1571">גַּ֣ם</w>';
chapter2 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/8145" n="1.2.1">הַ/שֵּׁנִ֗י</w>';
chapter2 += '		<w lemma="1571" n="1.2.0">גַּ֚ם</w>';
chapter2 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/7992" n="1.2">הַ/שְּׁלִישִׁ֔י</w>';
chapter2 += '		<w lemma="1571" n="1.1.0">גַּ֚ם</w>';
chapter2 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="d/1980" n="1.1">הַ/הֹ֣לְכִ֔ים</w>';
chapter2 += '		<w lemma="310 a">אַחֲרֵ֥י</w>';
chapter2 += '		<w lemma="d/5739" n="1.0">הָ/עֲדָרִ֖ים</w>';
chapter2 += '		<w lemma="l/559" n="1">לֵ/אמֹ֑ר</w>';
chapter2 += '		<w lemma="k/1697">כַּ/דָּבָ֤ר</w>';
chapter2 += '		<w lemma="d/2088" n="0.1.0">הַ/זֶּה֙</w>';
chapter2 += '		<w lemma="1696">תְּדַבְּר֣וּ/ן</w>';
chapter2 += '		<w lemma="413">אֶל</w><seg type="x-maqqef">־</seg><w lemma="6215" n="0.1">עֵשָׂ֔ו</w>';
chapter2 += '		<w lemma="b/4672" n="0.0">בְּ/מֹצַאֲ/כֶ֖ם</w>';
chapter2 += '		<w lemma="853" n="0">אֹתֽ/וֹ</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.21">';
chapter2 += '		<note>KJV:Gen.32.20</note>';
chapter2 += '		<w lemma="c/559" n="1.1">וַ/אֲמַרְתֶּ֕ם</w>';
chapter2 += '		<w lemma="1571" n="1.0.1">גַּ֗ם</w>';
chapter2 += '		<w lemma="2009" n="1.0.0">הִנֵּ֛ה</w>';
chapter2 += '		<w lemma="5650">עַבְדְּ/ךָ֥</w>';
chapter2 += '		<w lemma="3290" n="1.0">יַעֲקֹ֖ב</w>';
chapter2 += '		<w lemma="310 a" n="1">אַחֲרֵ֑י/נוּ</w>';
chapter2 += '		<w lemma="3588 a">כִּֽי</w><seg type="x-maqqef">־</seg><w lemma="559" n="0.2.1.0">אָמַ֞ר</w>';
chapter2 += '		<w lemma="3722 a">אֲכַפְּרָ֣ה</w>';
chapter2 += '		<w lemma="6440" n="0.2.1">פָנָ֗י/ו</w>';
chapter2 += '		<w lemma="b/4503" n="0.2.0">בַּ/מִּנְחָה֙</w>';
chapter2 += '		<w lemma="d/1980">הַ/הֹלֶ֣כֶת</w>';
chapter2 += '		<w lemma="l/6440" n="0.2">לְ/פָנָ֔/י</w>';
chapter2 += '		<w lemma="c/310 a">וְ/אַחֲרֵי</w><seg type="x-maqqef">־</seg><w lemma="3651 c" n="0.1.0">כֵן֙</w>';
chapter2 += '		<w lemma="7200">אֶרְאֶ֣ה</w>';
chapter2 += '		<w lemma="6440" n="0.1">פָנָ֔י/ו</w>';
chapter2 += '		<w lemma="194" n="0.0">אוּלַ֖י</w>';
chapter2 += '		<w lemma="5375">יִשָּׂ֥א</w>';
chapter2 += '		<w lemma="6440" n="0">פָנָֽ/י</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.22">';
chapter2 += '		<note>KJV:Gen.32.21</note>';
chapter2 += '		<w lemma="c/5674 a">וַ/תַּעֲבֹ֥ר</w>';
chapter2 += '		<w lemma="d/4503" n="1.0">הַ/מִּנְחָ֖ה</w>';
chapter2 += '		<w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="6440" n="1">פָּנָ֑י/ו</w>';
chapter2 += '		<w lemma="c/1931" n="0.0.0">וְ/ה֛וּא</w>';
chapter2 += '		<w lemma="3885 a">לָ֥ן</w>';
chapter2 += '		<w lemma="b/3915">בַּ/לַּֽיְלָה</w><seg type="x-maqqef">־</seg><w lemma="d/1931" n="0.0">הַ/ה֖וּא</w>';
chapter2 += '		<w lemma="b/4264" n="0">בַּֽ/מַּחֲנֶֽה</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.23">';
chapter2 += '		<note>KJV:Gen.32.22</note>';
chapter2 += '		<w lemma="c/6965 b" n="1.1.1.0">וַ/יָּ֣קָם</w>';
chapter2 += '		<seg type="x-paseq">׀</seg>';
chapter2 += '		<w lemma="b/3915">בַּ/לַּ֣יְלָה</w>';
chapter2 += '		<w lemma="1931" n="1.1.1">ה֗וּא</w>';
chapter2 += '		<w lemma="c/3947" n="1.1.0.0">וַ/יִּקַּ֞ח</w>';
chapter2 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="8147">שְׁתֵּ֤י</w>';
chapter2 += '		<w lemma="802" n="1.1.0">נָשָׁי/ו֙</w>';
chapter2 += '		<w lemma="c/853">וְ/אֶת</w><seg type="x-maqqef">־</seg><w lemma="8147">שְׁתֵּ֣י</w>';
chapter2 += '		<w lemma="8198" n="1.1">שִׁפְחֹתָ֔י/ו</w>';
chapter2 += '		<w lemma="c/853">וְ/אֶת</w><seg type="x-maqqef">־</seg><w lemma="259">אַחַ֥ד</w>';
chapter2 += '		<w lemma="6240" n="1.0">עָשָׂ֖ר</w>';
chapter2 += '		<w lemma="3206" n="1">יְלָדָ֑י/ו</w>';
chapter2 += '		<w lemma="c/5674 a" n="0.1">וַֽ/יַּעֲבֹ֔ר</w>';
chapter2 += '		<w lemma="853" n="0.0">אֵ֖ת</w>';
chapter2 += '		<w lemma="4569 a">מַעֲבַ֥ר</w>';
chapter2 += '		<w lemma="2999" n="0">יַבֹּֽק</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.24">';
chapter2 += '		<note>KJV:Gen.32.23</note>';
chapter2 += '		<w lemma="c/3947" n="1.1">וַ/יִּקָּחֵ֔/ם</w>';
chapter2 += '		<w lemma="c/5674 a" n="1.0">וַ/יַּֽעֲבִרֵ֖/ם</w>';
chapter2 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/5158 a" n="1">הַ/נָּ֑חַל</w>';
chapter2 += '		<w lemma="c/5674 a" n="0.0">וַֽ/יַּעֲבֵ֖ר</w>';
chapter2 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="834 a">אֲשֶׁר</w><seg type="x-maqqef">־</seg><w lemma="l" n="0">ל/וֹ</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '		<note n="1">BHS has been faithful to the Leningrad Codex where there might be a question of the validity of the form and we keep the same form as BHS. </note>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.25">';
chapter2 += '		<note>KJV:Gen.32.24</note>';
chapter2 += '		<w lemma="c/3498">וַ/יִּוָּתֵ֥ר</w>';
chapter2 += '		<w lemma="3290" n="1.0">יַעֲקֹ֖ב</w>';
chapter2 += '		<w lemma="l/905" n="1">לְ/בַדּ֑/וֹ</w>';
chapter2 += '		<w lemma="c/79">וַ/יֵּאָבֵ֥ק</w>';
chapter2 += '		<w lemma="582" n="0.1.0">אִישׁ֙</w>';
chapter2 += '		<w lemma="5973 a" n="0.1">עִמּ֔/וֹ</w>';
chapter2 += '		<w lemma="5704" n="0.0">עַ֖ד</w>';
chapter2 += '		<w lemma="5927">עֲל֥וֹת</w>';
chapter2 += '		<w lemma="d/7837" n="0">הַ/שָּֽׁחַר</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.26">';
chapter2 += '		<note>KJV:Gen.32.25</note>';
chapter2 += '		<w lemma="c/7200" n="1.1.1">וַ/יַּ֗רְא</w>';
chapter2 += '		<w lemma="3588 a">כִּ֣י</w>';
chapter2 += '		<w lemma="3808">לֹ֤א</w>';
chapter2 += '		<w lemma="3201" n="1.1.0">יָכֹל֙</w>';
chapter2 += '		<w lemma="l" n="1.1">ל֔/וֹ</w>';
chapter2 += '		<w lemma="c/5060" n="1.0">וַ/יִּגַּ֖ע</w>';
chapter2 += '		<w lemma="b/3709">בְּ/כַף</w><seg type="x-maqqef">־</seg><w lemma="3409" n="1">יְרֵכ֑/וֹ</w>';
chapter2 += '		<w lemma="c/3363" n="0.1.0">וַ/תֵּ֙קַע֙</w>';
chapter2 += '		<w lemma="3709">כַּף</w><seg type="x-maqqef">־</seg><w lemma="3409">יֶ֣רֶךְ</w>';
chapter2 += '		<w lemma="3290" n="0.1">יַעֲקֹ֔ב</w>';
chapter2 += '		<w lemma="b/79" n="0.0">בְּ/הֵֽאָבְק֖/וֹ</w>';
chapter2 += '		<w lemma="5973 a" n="0">עִמּֽ/וֹ</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.27">';
chapter2 += '		<note>KJV:Gen.32.26</note>';
chapter2 += '		<w lemma="c/559">וַ/יֹּ֣אמֶר</w>';
chapter2 += '		<w lemma="7971" n="1.1">שַׁלְּחֵ֔/נִי</w>';
chapter2 += '		<w lemma="3588 a">כִּ֥י</w>';
chapter2 += '		<w lemma="5927" n="1.0">עָלָ֖ה</w>';
chapter2 += '		<w lemma="d/7837" n="1">הַ/שָּׁ֑חַר</w>';
chapter2 += '		<w lemma="c/559" n="0.1.0">וַ/יֹּ֙אמֶר֙</w>';
chapter2 += '		<w lemma="3808">לֹ֣א</w>';
chapter2 += '		<w lemma="7971" n="0.1">אֲשַֽׁלֵּחֲ/ךָ֔</w>';
chapter2 += '		<w lemma="3588 b" n="0.0">כִּ֖י</w>';
chapter2 += '		<w lemma="518 b">אִם</w><seg type="x-maqqef">־</seg><w lemma="1288" n="0">בֵּרַכְתָּֽ/נִי</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.28">';
chapter2 += '		<note>KJV:Gen.32.27</note>';
chapter2 += '		<w lemma="c/559">וַ/יֹּ֥אמֶר</w>';
chapter2 += '		<w lemma="413" n="1.0">אֵלָ֖י/ו</w>';
chapter2 += '		<w lemma="4100">מַה</w><seg type="x-maqqef">־</seg><w lemma="8034" n="1">שְּׁמֶ֑/ךָ</w>';
chapter2 += '		<w lemma="c/559" n="0.0">וַ/יֹּ֖אמֶר</w>';
chapter2 += '		<w lemma="3290" n="0">יַעֲקֹֽב</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.29">';
chapter2 += '		<note>KJV:Gen.32.28</note>';
chapter2 += '		<w lemma="c/559" n="1.1.2">וַ/יֹּ֗אמֶר</w>';
chapter2 += '		<w lemma="3808">לֹ֤א</w>';
chapter2 += '		<w lemma="3290" n="1.1.1">יַעֲקֹב֙</w>';
chapter2 += '		<w lemma="559">יֵאָמֵ֥ר</w>';
chapter2 += '		<w lemma="5750" n="1.1.0">עוֹד֙</w>';
chapter2 += '		<w lemma="8034" n="1.1">שִׁמְ/ךָ֔</w>';
chapter2 += '		<w lemma="3588 b" n="1.0">כִּ֖י</w>';
chapter2 += '		<w lemma="518 b">אִם</w><seg type="x-maqqef">־</seg><w lemma="3478" n="1">יִשְׂרָאֵ֑ל</w>';
chapter2 += '		<w lemma="3588 a">כִּֽי</w><seg type="x-maqqef">־</seg><w lemma="8280">שָׂרִ֧יתָ</w>';
chapter2 += '		<w lemma="5973 a">עִם</w><seg type="x-maqqef">־</seg><w lemma="430" n="0.0.0">אֱלֹהִ֛ים</w>';
chapter2 += '		<w lemma="c/5973 a">וְ/עִם</w><seg type="x-maqqef">־</seg><w lemma="376" n="0.0">אֲנָשִׁ֖ים</w>';
chapter2 += '		<w lemma="c/3201" n="0">וַ/תּוּכָֽל</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.30">';
chapter2 += '		<note>KJV:Gen.32.29</note>';
chapter2 += '		<w lemma="c/7592">וַ/יִּשְׁאַ֣ל</w>';
chapter2 += '		<w lemma="3290" n="1.2.1">יַעֲקֹ֗ב</w>';
chapter2 += '		<w lemma="c/559" n="1.2.0">וַ/יֹּ֙אמֶר֙</w>';
chapter2 += '		<w lemma="5046">הַגִּֽידָ/ה</w><seg type="x-maqqef">־</seg><w lemma="4994">נָּ֣א</w>';
chapter2 += '		<w lemma="8034" n="1.2">שְׁמֶ֔/ךָ</w>';
chapter2 += '		<w lemma="c/559" n="1.1">וַ/יֹּ֕אמֶר</w>';
chapter2 += '		<w lemma="l/4100">לָ֥/מָּה</w>';
chapter2 += '		<w lemma="2088" n="1.0">זֶּ֖ה</w>';
chapter2 += '		<w lemma="7592">תִּשְׁאַ֣ל</w>';
chapter2 += '		<w lemma="l/8034" n="1">לִ/שְׁמִ֑/י</w>';
chapter2 += '		<w lemma="c/1288">וַ/יְבָ֥רֶךְ</w>';
chapter2 += '		<w lemma="853" n="0.0">אֹת֖/וֹ</w>';
chapter2 += '		<w lemma="8033" n="0">שָֽׁם</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.31">';
chapter2 += '		<note>KJV:Gen.32.30</note>';
chapter2 += '		<w lemma="c/7121">וַ/יִּקְרָ֧א</w>';
chapter2 += '		<w lemma="3290" n="1.0.0">יַעֲקֹ֛ב</w>';
chapter2 += '		<w lemma="8034">שֵׁ֥ם</w>';
chapter2 += '		<w lemma="d/4725" n="1.0">הַ/מָּק֖וֹם</w>';
chapter2 += '		<w lemma="6439" n="1">פְּנִיאֵ֑ל</w>';
chapter2 += '		<w lemma="3588 a">כִּֽי</w><seg type="x-maqqef">־</seg><w lemma="7200">רָאִ֤יתִי</w>';
chapter2 += '		<w lemma="430" n="0.1.0">אֱלֹהִים֙</w>';
chapter2 += '		<w lemma="6440">פָּנִ֣ים</w>';
chapter2 += '		<w lemma="413">אֶל</w><seg type="x-maqqef">־</seg><w lemma="6440" n="0.1">פָּנִ֔ים</w>';
chapter2 += '		<w lemma="c/5337" n="0.0">וַ/תִּנָּצֵ֖ל</w>';
chapter2 += '		<w lemma="5315" n="0">נַפְשִֽׁ/י</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.32">';
chapter2 += '		<note>KJV:Gen.32.31</note>';
chapter2 += '		<w lemma="c/2224">וַ/יִּֽזְרַֽח</w><seg type="x-maqqef">־</seg><w lemma="l">ל֣/וֹ</w>';
chapter2 += '		<w lemma="d/8121" n="1.1">הַ/שֶּׁ֔מֶשׁ</w>';
chapter2 += '		<w lemma="k/834 d">כַּ/אֲשֶׁ֥ר</w>';
chapter2 += '		<w lemma="5674 a" n="1.0">עָבַ֖ר</w>';
chapter2 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="6439" n="1">פְּנוּאֵ֑ל</w>';
chapter2 += '		<w lemma="c/1931">וְ/ה֥וּא</w>';
chapter2 += '		<w lemma="6760" n="0.0">צֹלֵ֖עַ</w>';
chapter2 += '		<w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="3409" n="0">יְרֵכֽ/וֹ</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '	<verse osisID="Gen.32.33">';
chapter2 += '		<note>KJV:Gen.32.32</note>';
chapter2 += '		<w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="3651 c" n="1.1.1.1">כֵּ֡ן</w>';
chapter2 += '		<w lemma="3808">לֹֽא</w><seg type="x-maqqef">־</seg><w lemma="398">יֹאכְל֨וּ</w>';
chapter2 += '		<w lemma="1121 a">בְנֵֽי</w><seg type="x-maqqef">־</seg><w lemma="3478" n="1.1.1.0">יִשְׂרָאֵ֜ל</w>';
chapter2 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="1517">גִּ֣יד</w>';
chapter2 += '		<w lemma="d/5384" n="1.1.1">הַ/נָּשֶׁ֗ה</w>';
chapter2 += '		<w lemma="834 a" n="1.1.0">אֲשֶׁר֙</w>';
chapter2 += '		<w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="3709">כַּ֣ף</w>';
chapter2 += '		<w lemma="d/3409" n="1.1">הַ/יָּרֵ֔ךְ</w>';
chapter2 += '		<w lemma="5704" n="1.0">עַ֖ד</w>';
chapter2 += '		<w lemma="d/3117">הַ/יּ֣וֹם</w>';
chapter2 += '		<w lemma="d/2088" n="1">הַ/זֶּ֑ה</w>';
chapter2 += '		<w lemma="3588 a">כִּ֤י</w>';
chapter2 += '		<w lemma="5060" n="0.1.0">נָגַע֙</w>';
chapter2 += '		<w lemma="b/3709">בְּ/כַף</w><seg type="x-maqqef">־</seg><w lemma="3409">יֶ֣רֶךְ</w>';
chapter2 += '		<w lemma="3290" n="0.1">יַעֲקֹ֔ב</w>';
chapter2 += '		<w lemma="b/1517" n="0.0">בְּ/גִ֖יד</w>';
chapter2 += '		<w lemma="d/5384" n="0">הַ/נָּשֶֽׁה</w><seg type="x-sof-pasuq">׃</seg>';
chapter2 += '	</verse>';
chapter2 += '</chapter>';