chapter1 = '<?xml version="1.0" encoding="UTF-8"?>';
chapter1 += '<chapter osisID="Gen.8">';
chapter1 += '	<verse osisID="Gen.8.1">';
chapter1 += '		<w lemma="c/2142">וַ/יִּזְכֹּ֤ר</w>';
chapter1 += '		<w lemma="430" n="1.2.0">אֱלֹהִים֙</w>';
chapter1 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="5146" n="1.2">נֹ֔חַ</w>';
chapter1 += '		<w lemma="c/853">וְ/אֵ֤ת</w>';
chapter1 += '		<w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="d/2416 c" n="1.1.0">הַֽ/חַיָּה֙</w>';
chapter1 += '		<w lemma="c/853">וְ/אֶת</w><seg type="x-maqqef">־</seg><w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="d/929" n="1.1">הַ/בְּהֵמָ֔ה</w>';
chapter1 += '		<w lemma="834 a">אֲשֶׁ֥ר</w>';
chapter1 += '		<w lemma="854" n="1.0">אִתּ֖/וֹ</w>';
chapter1 += '		<w lemma="b/8392" n="1">בַּ/תֵּבָ֑ה</w>';
chapter1 += '		<w lemma="c/5674 a">וַ/יַּעֲבֵ֨ר</w>';
chapter1 += '		<w lemma="430">אֱלֹהִ֥ים</w>';
chapter1 += '		<w lemma="7307" n="0.1.0">ר֙וּחַ֙</w>';
chapter1 += '		<w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="0.1">הָ/אָ֔רֶץ</w>';
chapter1 += '		<w lemma="c/7918" n="0.0">וַ/יָּשֹׁ֖כּוּ</w>';
chapter1 += '		<w lemma="d/4325" n="0">הַ/מָּֽיִם</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.2">';
chapter1 += '		<w lemma="c/5534" n="1.1.0">וַ/יִּסָּֽכְרוּ֙</w>';
chapter1 += '		<w lemma="4599">מַעְיְנֹ֣ת</w>';
chapter1 += '		<w lemma="8415" n="1.1">תְּה֔וֹם</w>';
chapter1 += '		<w lemma="c/699" n="1.0">וַֽ/אֲרֻבֹּ֖ת</w>';
chapter1 += '		<w lemma="d/8064" n="1">הַ/שָּׁמָ֑יִם</w>';
chapter1 += '		<w lemma="c/3607">וַ/יִּכָּלֵ֥א</w>';
chapter1 += '		<w lemma="d/1653" n="0.0">הַ/גֶּ֖שֶׁם</w>';
chapter1 += '		<w lemma="4480 a">מִן</w><seg type="x-maqqef">־</seg><w lemma="d/8064" n="0">הַ/שָּׁמָֽיִם</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.3">';
chapter1 += '		<w lemma="c/7725">וַ/יָּשֻׁ֧בוּ</w>';
chapter1 += '		<w lemma="d/4325" n="1.0.0">הַ/מַּ֛יִם</w>';
chapter1 += '		<w lemma="m/5921 a">מֵ/עַ֥ל</w>';
chapter1 += '		<w lemma="d/776" n="1.0">הָ/אָ֖רֶץ</w>';
chapter1 += '		<w lemma="1980">הָל֣וֹךְ</w>';
chapter1 += '		<w lemma="c/7725" n="1">וָ/שׁ֑וֹב</w>';
chapter1 += '		<w lemma="c/2637">וַ/יַּחְסְר֣וּ</w>';
chapter1 += '		<w lemma="d/4325" n="0.2">הַ/מַּ֔יִם</w>';
chapter1 += '		<w lemma="m/7097 a" n="0.1">מִ/קְצֵ֕ה</w>';
chapter1 += '		<w lemma="2572">חֲמִשִּׁ֥ים</w>';
chapter1 += '		<w lemma="c/3967" n="0.0">וּ/מְאַ֖ת</w>';
chapter1 += '		<w lemma="3117" n="0">יֽוֹם</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.4">';
chapter1 += '		<w lemma="c/5117">וַ/תָּ֤נַח</w>';
chapter1 += '		<w lemma="d/8392" n="1.1.0">הַ/תֵּבָה֙</w>';
chapter1 += '		<w lemma="b/2320">בַּ/חֹ֣דֶשׁ</w>';
chapter1 += '		<w lemma="d/7637" n="1.1">הַ/שְּׁבִיעִ֔י</w>';
chapter1 += '		<w lemma="b/7651">בְּ/שִׁבְעָה</w><seg type="x-maqqef">־</seg><w lemma="6240">עָשָׂ֥ר</w>';
chapter1 += '		<w lemma="3117" n="1.0">י֖וֹם</w>';
chapter1 += '		<w lemma="l/2320" n="1">לַ/חֹ֑דֶשׁ</w>';
chapter1 += '		<w lemma="5921 a" n="0.0">עַ֖ל</w>';
chapter1 += '		<w lemma="2022">הָרֵ֥י</w>';
chapter1 += '		<w lemma="780" n="0">אֲרָרָֽט</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.5">';
chapter1 += '		<w lemma="c/d/4325" n="1.1.1">וְ/הַ/מַּ֗יִם</w>';
chapter1 += '		<w lemma="1961" n="1.1.0">הָיוּ֙</w>';
chapter1 += '		<w lemma="1980">הָל֣וֹךְ</w>';
chapter1 += '		<w lemma="c/2637" n="1.1">וְ/חָס֔וֹר</w>';
chapter1 += '		<w lemma="5704" n="1.0">עַ֖ד</w>';
chapter1 += '		<w lemma="d/2320">הַ/חֹ֣דֶשׁ</w>';
chapter1 += '		<w lemma="d/6224" n="1">הָֽ/עֲשִׂירִ֑י</w>';
chapter1 += '		<w lemma="b/6224" n="0.1.0">בָּֽ/עֲשִׂירִי֙</w>';
chapter1 += '		<w lemma="b/259">בְּ/אֶחָ֣ד</w>';
chapter1 += '		<w lemma="l/2320" n="0.1">לַ/חֹ֔דֶשׁ</w>';
chapter1 += '		<w lemma="7200" n="0.0">נִרְא֖וּ</w>';
chapter1 += '		<w lemma="7218 a">רָאשֵׁ֥י</w>';
chapter1 += '		<w lemma="d/2022" n="0">הֶֽ/הָרִֽים</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.6">';
chapter1 += '		<w lemma="c/1961" n="1.1">וַֽ/יְהִ֕י</w>';
chapter1 += '		<w lemma="m/7093" n="1.0">מִ/קֵּ֖ץ</w>';
chapter1 += '		<w lemma="705">אַרְבָּעִ֣ים</w>';
chapter1 += '		<w lemma="3117" n="1">י֑וֹם</w>';
chapter1 += '		<w lemma="c/6605 a">וַ/יִּפְתַּ֣ח</w>';
chapter1 += '		<w lemma="5146" n="0.1">נֹ֔חַ</w>';
chapter1 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="2474">חַלּ֥וֹן</w>';
chapter1 += '		<w lemma="d/8392" n="0.0">הַ/תֵּבָ֖ה</w>';
chapter1 += '		<w lemma="834 a">אֲשֶׁ֥ר</w>';
chapter1 += '		<w lemma="6213 a" n="0">עָשָֽׂה</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.7">';
chapter1 += '		<w lemma="c/7971" n="1.0">וַ/יְשַׁלַּ֖ח</w>';
chapter1 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/6158" n="1">הָֽ/עֹרֵ֑ב</w>';
chapter1 += '		<w lemma="c/3318">וַ/יֵּצֵ֤א</w>';
chapter1 += '		<w lemma="3318" n="0.1.0">יָצוֹא֙</w>';
chapter1 += '		<w lemma="c/7725" n="0.1">וָ/שׁ֔וֹב</w>';
chapter1 += '		<w lemma="5704">עַד</w><seg type="x-maqqef">־</seg><w lemma="3001">יְבֹ֥שֶׁת</w>';
chapter1 += '		<w lemma="d/4325" n="0.0">הַ/מַּ֖יִם</w>';
chapter1 += '		<w lemma="m/5921 a">מֵ/עַ֥ל</w>';
chapter1 += '		<w lemma="d/776" n="0">הָ/אָֽרֶץ</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.8">';
chapter1 += '		<w lemma="c/7971">וַ/יְשַׁלַּ֥ח</w>';
chapter1 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/3123" n="1.0">הַ/יּוֹנָ֖ה</w>';
chapter1 += '		<w lemma="m/854" n="1">מֵ/אִתּ֑/וֹ</w>';
chapter1 += '		<w lemma="l/7200" n="0.1.0">לִ/רְאוֹת֙</w>';
chapter1 += '		<w lemma="i/7043">הֲ/קַ֣לּוּ</w>';
chapter1 += '		<w lemma="d/4325" n="0.1">הַ/מַּ֔יִם</w>';
chapter1 += '		<w lemma="m/5921 a" n="0.0">מֵ/עַ֖ל</w>';
chapter1 += '		<w lemma="6440">פְּנֵ֥י</w>';
chapter1 += '		<w lemma="d/127" n="0">הָֽ/אֲדָמָֽה</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.9">';
chapter1 += '		<w lemma="c/3808">וְ/לֹֽא</w><seg type="x-maqqef">־</seg><w lemma="4672">מָצְאָה֩</w>';
chapter1 += '		<w lemma="d/3123">הַ/יּוֹנָ֨ה</w>';
chapter1 += '		<w lemma="4494" n="1.1.1.0">מָנ֜וֹחַ</w>';
chapter1 += '		<w lemma="l/3709">לְ/כַף</w><seg type="x-maqqef">־</seg><w lemma="7272" n="1.1.1">רַגְלָ֗/הּ</w>';
chapter1 += '		<w lemma="c/7725">וַ/תָּ֤שָׁב</w>';
chapter1 += '		<w lemma="413" n="1.1.0">אֵלָי/ו֙</w>';
chapter1 += '		<w lemma="413">אֶל</w><seg type="x-maqqef">־</seg><w lemma="d/8392" n="1.1">הַ/תֵּבָ֔ה</w>';
chapter1 += '		<w lemma="3588 a">כִּי</w><seg type="x-maqqef">־</seg><w lemma="4325" n="1.0">מַ֖יִם</w>';
chapter1 += '		<w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="6440">פְּנֵ֣י</w>';
chapter1 += '		<w lemma="3605">כָל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="1">הָ/אָ֑רֶץ</w>';
chapter1 += '		<w lemma="c/7971">וַ/יִּשְׁלַ֤ח</w>';
chapter1 += '		<w lemma="3027" n="0.1.0">יָד/וֹ֙</w>';
chapter1 += '		<w lemma="c/3947" n="0.1">וַ/יִּקָּחֶ֔/הָ</w>';
chapter1 += '		<w lemma="c/935">וַ/יָּבֵ֥א</w>';
chapter1 += '		<w lemma="853" n="0.0.0">אֹתָ֛/הּ</w>';
chapter1 += '		<w lemma="413" n="0.0">אֵלָ֖י/ו</w>';
chapter1 += '		<w lemma="413">אֶל</w><seg type="x-maqqef">־</seg><w lemma="d/8392" n="0">הַ/תֵּבָֽה</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.10">';
chapter1 += '		<w lemma="c/2342 a">וַ/יָּ֣חֶל</w>';
chapter1 += '		<w lemma="5750" n="1.1">ע֔וֹד</w>';
chapter1 += '		<w lemma="7651">שִׁבְעַ֥ת</w>';
chapter1 += '		<w lemma="3117" n="1.0">יָמִ֖ים</w>';
chapter1 += '		<w lemma="312" n="1">אֲחֵרִ֑ים</w>';
chapter1 += '		<w lemma="c/3254" n="0.0.0">וַ/יֹּ֛סֶף</w>';
chapter1 += '		<w lemma="7971">שַׁלַּ֥ח</w>';
chapter1 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/3123" n="0.0">הַ/יּוֹנָ֖ה</w>';
chapter1 += '		<w lemma="4480 a">מִן</w><seg type="x-maqqef">־</seg><w lemma="d/8392" n="0">הַ/תֵּבָֽה</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.11">';
chapter1 += '		<w lemma="c/935">וַ/תָּבֹ֨א</w>';
chapter1 += '		<w lemma="413">אֵלָ֤י/ו</w>';
chapter1 += '		<w lemma="d/3123" n="1.1.0">הַ/יּוֹנָה֙</w>';
chapter1 += '		<w lemma="l/6256">לְ/עֵ֣ת</w>';
chapter1 += '		<w lemma="6153" n="1.1">עֶ֔רֶב</w>';
chapter1 += '		<w lemma="c/2009">וְ/הִנֵּ֥ה</w>';
chapter1 += '		<w lemma="5929">עֲלֵה</w><seg type="x-maqqef">־</seg><w lemma="2132" n="1.0">זַ֖יִת</w>';
chapter1 += '		<w lemma="2965">טָרָ֣ף</w>';
chapter1 += '		<w lemma="b/6310" n="1">בְּ/פִ֑י/הָ</w>';
chapter1 += '		<w lemma="c/3045">וַ/יֵּ֣דַע</w>';
chapter1 += '		<w lemma="5146" n="0.1">נֹ֔חַ</w>';
chapter1 += '		<w lemma="3588 a">כִּי</w><seg type="x-maqqef">־</seg><w lemma="7043">קַ֥לּוּ</w>';
chapter1 += '		<w lemma="d/4325" n="0.0">הַ/מַּ֖יִם</w>';
chapter1 += '		<w lemma="m/5921 a">מֵ/עַ֥ל</w>';
chapter1 += '		<w lemma="d/776" n="0">הָ/אָֽרֶץ</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.12">';
chapter1 += '		<w lemma="c/3176">וַ/יִּיָּ֣חֶל</w>';
chapter1 += '		<w lemma="5750" n="1.1">ע֔וֹד</w>';
chapter1 += '		<w lemma="7651">שִׁבְעַ֥ת</w>';
chapter1 += '		<w lemma="3117" n="1.0">יָמִ֖ים</w>';
chapter1 += '		<w lemma="312" n="1">אֲחֵרִ֑ים</w>';
chapter1 += '		<w lemma="c/7971" n="0.1.0">וַ/יְשַׁלַּח֙</w>';
chapter1 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/3123" n="0.1">הַ/יּוֹנָ֔ה</w>';
chapter1 += '		<w lemma="c/3808">וְ/לֹֽא</w><seg type="x-maqqef">־</seg><w lemma="3254">יָסְפָ֥ה</w>';
chapter1 += '		<w lemma="7725">שׁוּב</w><seg type="x-maqqef">־</seg><w lemma="413" n="0.0">אֵלָ֖י/ו</w>';
chapter1 += '		<w lemma="5750" n="0">עֽוֹד</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.13">';
chapter1 += '		<w lemma="c/1961" n="1.1.1.1">וַֽ֠/יְהִי</w>';
chapter1 += '		<w lemma="b/259">בְּ/אַחַ֨ת</w>';
chapter1 += '		<w lemma="c/8337">וְ/שֵׁשׁ</w><seg type="x-maqqef">־</seg><w lemma="3967" n="1.1.1.0">מֵא֜וֹת</w>';
chapter1 += '		<w lemma="8141" n="1.1.1">שָׁנָ֗ה</w>';
chapter1 += '		<w lemma="b/7223" n="1.1.0">בָּֽ/רִאשׁוֹן֙</w>';
chapter1 += '		<w lemma="b/259">בְּ/אֶחָ֣ד</w>';
chapter1 += '		<w lemma="l/2320" n="1.1">לַ/חֹ֔דֶשׁ</w>';
chapter1 += '		<w lemma="2717 a">חָֽרְב֥וּ</w>';
chapter1 += '		<w lemma="d/4325" n="1.0">הַ/מַּ֖יִם</w>';
chapter1 += '		<w lemma="m/5921 a">מֵ/עַ֣ל</w>';
chapter1 += '		<w lemma="d/776" n="1">הָ/אָ֑רֶץ</w>';
chapter1 += '		<w lemma="c/5493">וַ/יָּ֤סַר</w>';
chapter1 += '		<w lemma="5146" n="0.2.0">נֹ֙חַ֙</w>';
chapter1 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="4372">מִכְסֵ֣ה</w>';
chapter1 += '		<w lemma="d/8392" n="0.2">הַ/תֵּבָ֔ה</w>';
chapter1 += '		<w lemma="c/7200" n="0.1">וַ/יַּ֕רְא</w>';
chapter1 += '		<w lemma="c/2009">וְ/הִנֵּ֥ה</w>';
chapter1 += '		<w lemma="2717 a" n="0.0">חָֽרְב֖וּ</w>';
chapter1 += '		<w lemma="6440">פְּנֵ֥י</w>';
chapter1 += '		<w lemma="d/127" n="0">הָֽ/אֲדָמָֽה</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.14">';
chapter1 += '		<w lemma="c/b/2320" n="1.1.0">וּ/בַ/חֹ֙דֶשׁ֙</w>';
chapter1 += '		<w lemma="d/8145" n="1.1">הַ/שֵּׁנִ֔י</w>';
chapter1 += '		<w lemma="b/7651">בְּ/שִׁבְעָ֧ה</w>';
chapter1 += '		<w lemma="c/6242" n="1.0.0">וְ/עֶשְׂרִ֛ים</w>';
chapter1 += '		<w lemma="3117" n="1.0">י֖וֹם</w>';
chapter1 += '		<w lemma="l/2320" n="1">לַ/חֹ֑דֶשׁ</w>';
chapter1 += '		<w lemma="3001" n="0.0">יָבְשָׁ֖ה</w>';
chapter1 += '		<w lemma="d/776" n="0">הָ/אָֽרֶץ</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '		<seg type="x-samekh">ס</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.15">';
chapter1 += '		<w lemma="c/1696">וַ/יְדַבֵּ֥ר</w>';
chapter1 += '		<w lemma="430" n="0.0">אֱלֹהִ֖ים</w>';
chapter1 += '		<w lemma="413">אֶל</w><seg type="x-maqqef">־</seg><w lemma="5146">נֹ֥חַ</w>';
chapter1 += '		<w lemma="l/559" n="0">לֵ/אמֹֽר</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.16">';
chapter1 += '		<w lemma="3318" n="1.0">צֵ֖א</w>';
chapter1 += '		<w lemma="4480 a">מִן</w><seg type="x-maqqef">־</seg><w lemma="d/8392" n="1">הַ/תֵּבָ֑ה</w>';
chapter1 += '		<w lemma="859 a" n="0.1">אַתָּ֕ה</w>';
chapter1 += '		<w lemma="c/802" n="0.0.0">וְ/אִשְׁתְּ/ךָ֛</w>';
chapter1 += '		<w lemma="c/1121 a">וּ/בָנֶ֥י/ךָ</w>';
chapter1 += '		<w lemma="c/802">וּ/נְשֵֽׁי</w><seg type="x-maqqef">־</seg><w lemma="1121 a" n="0.0">בָנֶ֖י/ךָ</w>';
chapter1 += '		<w lemma="854" n="0">אִתָּֽ/ךְ</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.17">';
chapter1 += '		<w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="d/2416 c">הַ/חַיָּ֨ה</w>';
chapter1 += '		<w lemma="834 a">אֲשֶֽׁר</w><seg type="x-maqqef">־</seg><w lemma="854" n="1.0.2.0">אִתְּ/ךָ֜</w>';
chapter1 += '		<w lemma="m/3605">מִ/כָּל</w><seg type="x-maqqef">־</seg><w lemma="1320" n="1.0.2">בָּשָׂ֗ר</w>';
chapter1 += '		<w lemma="b/5775">בָּ/ע֧וֹף</w>';
chapter1 += '		<w lemma="c/b/929" n="1.0.1">וּ/בַ/בְּהֵמָ֛ה</w>';
chapter1 += '		<w lemma="c/b/3605">וּ/בְ/כָל</w><seg type="x-maqqef">־</seg><w lemma="d/7431" n="1.0.0">הָ/רֶ֛מֶשׂ</w>';
chapter1 += '		<w lemma="d/7430">הָ/רֹמֵ֥שׂ</w>';
chapter1 += '		<w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="1.0">הָ/אָ֖רֶץ</w>';
chapter1 += '		<w lemma="3318">הוצא</w><note type="variant"><catchWord>הוצא</catchWord><rdg type="x-qere"><w lemma="3318">הַיְצֵ֣א</w></rdg></note>';
chapter1 += '		<w lemma="854" n="1">אִתָּ֑/ךְ</w>';
chapter1 += '		<w lemma="c/8317">וְ/שָֽׁרְצ֣וּ</w>';
chapter1 += '		<w lemma="b/776" n="0.1">בָ/אָ֔רֶץ</w>';
chapter1 += '		<w lemma="c/6509">וּ/פָר֥וּ</w>';
chapter1 += '		<w lemma="c/7235 a" n="0.0">וְ/רָב֖וּ</w>';
chapter1 += '		<w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="0">הָ/אָֽרֶץ</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.18">';
chapter1 += '		<w lemma="c/3318">וַ/יֵּ֖צֵא</w><seg type="x-maqqef">־</seg><w lemma="5146" n="1">נֹ֑חַ</w>';
chapter1 += '		<w lemma="c/1121 a" n="0.0.0">וּ/בָנָ֛י/ו</w>';
chapter1 += '		<w lemma="c/802">וְ/אִשְׁתּ֥/וֹ</w>';
chapter1 += '		<w lemma="c/802">וּ/נְשֵֽׁי</w><seg type="x-maqqef">־</seg><w lemma="1121 a" n="0.0">בָנָ֖י/ו</w>';
chapter1 += '		<w lemma="854" n="0">אִתּֽ/וֹ</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.19">';
chapter1 += '		<w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="d/2416 c" n="1.1.1">הַֽ/חַיָּ֗ה</w>';
chapter1 += '		<w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="d/7431" n="1.1.0">הָ/רֶ֙מֶשׂ֙</w>';
chapter1 += '		<w lemma="c/3605">וְ/כָל</w><seg type="x-maqqef">־</seg><w lemma="d/5775" n="1.1">הָ/ע֔וֹף</w>';
chapter1 += '		<w lemma="3605" n="1.0">כֹּ֖ל</w>';
chapter1 += '		<w lemma="7430">רוֹמֵ֣שׂ</w>';
chapter1 += '		<w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="d/776" n="1">הָ/אָ֑רֶץ</w>';
chapter1 += '		<w lemma="l/4940" n="0.1">לְ/מִשְׁפְּחֹ֣תֵי/הֶ֔ם</w>';
chapter1 += '		<w lemma="3318" n="0.0">יָצְא֖וּ</w>';
chapter1 += '		<w lemma="4480 a">מִן</w><seg type="x-maqqef">־</seg><w lemma="d/8392" n="0">הַ/תֵּבָֽה</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.20">';
chapter1 += '		<w lemma="c/1129">וַ/יִּ֥בֶן</w>';
chapter1 += '		<w lemma="5146" n="1.0.0">נֹ֛חַ</w>';
chapter1 += '		<w lemma="4196" n="1.0">מִזְבֵּ֖חַ</w>';
chapter1 += '		<w lemma="l/3068" n="1">לַֽ/יהוָ֑ה</w>';
chapter1 += '		<w lemma="c/3947" n="0.1.1.1">וַ/יִּקַּ֞ח</w>';
chapter1 += '		<w lemma="m/3605" n="0.1.1.0">מִ/כֹּ֣ל</w>';
chapter1 += '		<seg type="x-paseq">׀</seg>';
chapter1 += '		<w lemma="d/929">הַ/בְּהֵמָ֣ה</w>';
chapter1 += '		<w lemma="d/2889" n="0.1.1">הַ/טְּהוֹרָ֗ה</w>';
chapter1 += '		<w lemma="c/m/3605" n="0.1.0">וּ/מִ/כֹּל֙</w>';
chapter1 += '		<w lemma="d/5775">הָ/ע֣וֹף</w>';
chapter1 += '		<w lemma="d/2889" n="0.1">הַ/טָּהֹ֔ר</w>';
chapter1 += '		<w lemma="c/5927">וַ/יַּ֥עַל</w>';
chapter1 += '		<w lemma="5930 a" n="0.0">עֹלֹ֖ת</w>';
chapter1 += '		<w lemma="b/4196" n="0">בַּ/מִּזְבֵּֽחַ</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.21">';
chapter1 += '		<w lemma="c/7306">וַ/יָּ֣רַח</w>';
chapter1 += '		<w lemma="3068" n="1.2.0">יְהוָה֮</w>';
chapter1 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="7381">רֵ֣יחַ</w>';
chapter1 += '		<w lemma="d/5207" n="1.2">הַ/נִּיחֹחַ֒</w>';
chapter1 += '		<w lemma="c/559">וַ/יֹּ֨אמֶר</w>';
chapter1 += '		<w lemma="3068" n="1.1.1.0">יְהוָ֜ה</w>';
chapter1 += '		<w lemma="413">אֶל</w><seg type="x-maqqef">־</seg><w lemma="3820 a" n="1.1.1">לִבּ֗/וֹ</w>';
chapter1 += '		<w lemma="3808">לֹֽא</w><seg type="x-maqqef">־</seg><w lemma="3254" n="1.1.0.0">אֹ֠סִף</w>';
chapter1 += '		<w lemma="l/7043">לְ/קַלֵּ֨ל</w>';
chapter1 += '		<w lemma="5750">ע֤וֹד</w>';
chapter1 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="d/127" n="1.1.0">הָֽ/אֲדָמָה֙</w>';
chapter1 += '		<w lemma="b/5668">בַּ/עֲב֣וּר</w>';
chapter1 += '		<w lemma="d/120" n="1.1">הָֽ/אָדָ֔ם</w>';
chapter1 += '		<w lemma="3588 a" n="1.0.0.0">כִּ֠י</w>';
chapter1 += '		<w lemma="3336">יֵ֣צֶר</w>';
chapter1 += '		<w lemma="3820 a">לֵ֧ב</w>';
chapter1 += '		<w lemma="d/120" n="1.0.0">הָ/אָדָ֛ם</w>';
chapter1 += '		<w lemma="7451 a" n="1.0">רַ֖ע</w>';
chapter1 += '		<w lemma="m/5271 a" n="1">מִ/נְּעֻרָ֑י/ו</w>';
chapter1 += '		<w lemma="c/3808">וְ/לֹֽא</w><seg type="x-maqqef">־</seg><w lemma="3254">אֹסִ֥ף</w>';
chapter1 += '		<w lemma="5750" n="0.0.0">ע֛וֹד</w>';
chapter1 += '		<w lemma="l/5221">לְ/הַכּ֥וֹת</w>';
chapter1 += '		<w lemma="853">אֶת</w><seg type="x-maqqef">־</seg><w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="2416 a" n="0.0">חַ֖י</w>';
chapter1 += '		<w lemma="k/834 d">כַּֽ/אֲשֶׁ֥ר</w>';
chapter1 += '		<w lemma="6213 a" n="0">עָשִֽׂיתִי</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '	<verse osisID="Gen.8.22">';
chapter1 += '		<w lemma="5750" n="1.0">עֹ֖ד</w>';
chapter1 += '		<w lemma="3605">כָּל</w><seg type="x-maqqef">־</seg><w lemma="3117">יְמֵ֣י</w>';
chapter1 += '		<w lemma="d/776" n="1">הָ/אָ֑רֶץ</w>';
chapter1 += '		<w lemma="2233" n="0.0.0.2">זֶ֡רַע</w>';
chapter1 += '		<w lemma="c/7105 a" n="0.0.0.1">וְ֠/קָצִיר</w>';
chapter1 += '		<w lemma="c/7120">וְ/קֹ֨ר</w>';
chapter1 += '		<w lemma="c/2527" n="0.0.0.0">וָ/חֹ֜ם</w>';
chapter1 += '		<w lemma="c/7019">וְ/קַ֧יִץ</w>';
chapter1 += '		<w lemma="c/2779" n="0.0.0">וָ/חֹ֛רֶף</w>';
chapter1 += '		<w lemma="c/3117">וְ/י֥וֹם</w>';
chapter1 += '		<w lemma="c/3915" n="0.0">וָ/לַ֖יְלָה</w>';
chapter1 += '		<w lemma="3808">לֹ֥א</w>';
chapter1 += '		<w lemma="7673 a" n="0">יִשְׁבֹּֽתוּ</w><seg type="x-sof-pasuq">׃</seg>';
chapter1 += '	</verse>';
chapter1 += '</chapter>';