chapter3 = '<?xml version="1.0" encoding="UTF-8"?>';
chapter3 += '<chapter osisID="Ps.1">';
chapter3 += '  <verse osisID="Ps.1.1">';
chapter3 += '    <w lemma="835" morph="HNcmpc">אַ֥שְֽׁרֵי</w><seg type="x-maqqef">־</seg><w lemma="d/376" n="2.1" morph="HTd/Ncmsa">הָ/אִ֗ישׁ</w>';
chapter3 += '    <note n="c">We read one or more accents in L differently than BHS. Often this notation indicates a typographical error in BHS. </note>';
chapter3 += '    <w lemma="834 a" n="2.0.0" morph="HTr">אֲשֶׁ֤ר</w>';
chapter3 += '    <seg type="x-paseq">׀</seg>';
chapter3 += '    <w lemma="3808" morph="HTn">לֹ֥א</w>';
chapter3 += '    <w lemma="1980" n="2.0" morph="HVqp3ms">הָלַךְ֮</w>';
chapter3 += '    <w lemma="b/6098" morph="HR/Ncfsc">בַּ/עֲצַ֪ת</w>';
chapter3 += '    <w lemma="7563" n="2" morph="HAampa">רְשָׁ֫עִ֥ים</w>';
chapter3 += '    <w lemma="c/b/1870" morph="HR/R/Ncmsc">וּ/בְ/דֶ֣רֶךְ</w>';
chapter3 += '    <w lemma="2400" n="1.0" morph="HAampa">חַ֭טָּאִים</w>';
chapter3 += '    <w lemma="3808" morph="HTn">לֹ֥א</w>';
chapter3 += '    <w lemma="5975" n="1" morph="HVqp3ms">עָמָ֑ד</w>';
chapter3 += '    <w lemma="c/b/4186" morph="HC/R/Ncmsc">וּ/בְ/מוֹשַׁ֥ב</w>';
chapter3 += '    <w lemma="3887" n="0.0" morph="HNcmpa">לֵ֝צִ֗ים</w>';
chapter3 += '    <w lemma="3808" morph="HTn">לֹ֣א</w>';
chapter3 += '    <w lemma="3427" n="0" morph="HVqp3ms">יָשָֽׁב</w><seg type="x-sof-pasuq">׃</seg>';
chapter3 += '  </verse>';
chapter3 += '  <verse osisID="Ps.1.2">';
chapter3 += '    <w lemma="3588 a" morph="HC">כִּ֤י</w>';
chapter3 += '    <w lemma="518 a" morph="HC">אִ֥ם</w>';
chapter3 += '    <w lemma="b/8451" morph="HR/Ncfsc">בְּ/תוֹרַ֥ת</w>';
chapter3 += '    <w lemma="3068" n="2.0" morph="HNp">יְהוָ֗ה</w>';
chapter3 += '    <w lemma="2656" n="2" morph="HNcmsc/Sp3ms">חֶ֫פְצ֥/וֹ</w>';
chapter3 += '    <w lemma="c/b/8451" morph="HC/R/Ncfsc/Sp3ms">וּֽ/בְ/תוֹרָת֥/וֹ</w>';
chapter3 += '    <w lemma="1897" n="1" morph="HVqi3ms">יֶהְגֶּ֗ה</w>';
chapter3 += '    <w lemma="3119" morph="HD">יוֹמָ֥ם</w>';
chapter3 += '    <w lemma="c/3915" n="0" morph="HC/Ncmsa">וָ/לָֽיְלָה</w><seg type="x-sof-pasuq">׃</seg>';
chapter3 += '  </verse>';
chapter3 += '  <verse osisID="Ps.1.3">';
chapter3 += '    <w lemma="c/1961" n="2.1" morph="HC/Vqq3ms">וְֽ/הָיָ֗ה</w>';
chapter3 += '    <w lemma="k/6086" n="2.0" morph="HR/Ncmsa">כְּ/עֵץ֮</w>';
chapter3 += '    <w lemma="8362" morph="HVqsmsa">שָׁת֪וּל</w>';
chapter3 += '    <w lemma="5921 a" morph="HR">עַֽל</w><seg type="x-maqqef">־</seg><w lemma="6388" morph="HNcmpc">פַּלְגֵ֫י</w>';
chapter3 += '    <w lemma="4325" n="2" morph="HNcmpa">מָ֥יִם</w>';
chapter3 += '    <w lemma="834 a" morph="HTr">אֲשֶׁ֤ר</w>';
chapter3 += '    <w lemma="6529" n="1.0.0" morph="HNcmsc/Sp3ms">פִּרְי֨/וֹ</w>';
chapter3 += '    <seg type="x-paseq">׀</seg>';
chapter3 += '    <w lemma="5414" morph="HVqi3ms">יִתֵּ֬ן</w>';
chapter3 += '    <w lemma="b/6256" n="1.0" morph="HR/Ncbsc/Sp3ms">בְּ/עִתּ֗/וֹ</w>';
chapter3 += '    <w lemma="c/5929" morph="HC/Ncmsc/Sp3ms">וְ/עָלֵ֥/הוּ</w>';
chapter3 += '    <w lemma="3808" morph="HTn">לֹֽא</w><seg type="x-maqqef">־</seg><w lemma="5034 b" n="1" morph="HVqi3ms">יִבּ֑וֹל</w>';
chapter3 += '    <w lemma="c/3605" morph="HC/Ncmsa">וְ/כֹ֖ל</w>';
chapter3 += '    <w lemma="834 a" morph="HTr">אֲשֶׁר</w><seg type="x-maqqef">־</seg><w lemma="6213 a" morph="HVqi3ms">יַעֲשֶׂ֣ה</w>';
chapter3 += '    <w lemma="6743 b" n="0" morph="HVhi3ms">יַצְלִֽיחַ</w><seg type="x-sof-pasuq">׃</seg>';
chapter3 += '  </verse>';
chapter3 += '  <verse osisID="Ps.1.4">';
chapter3 += '    <w lemma="3808" morph="HTn">לֹא</w><seg type="x-maqqef">־</seg><w lemma="3651 c" morph="HD">כֵ֥ן</w>';
chapter3 += '    <w lemma="d/7563" n="1" morph="HTd/Aampa">הָ/רְשָׁעִ֑ים</w>';
chapter3 += '    <w lemma="3588 b" morph="HC">כִּ֥י</w>';
chapter3 += '    <w lemma="518 b" morph="HC">אִם</w><seg type="x-maqqef">־</seg><w lemma="k/4671" n="0.0" morph="HRd/Ncmsa">כַּ֝/מֹּ֗ץ</w>';
chapter3 += '    <w lemma="834 a" morph="HTr">אֲֽשֶׁר</w><seg type="x-maqqef">־</seg><w lemma="5086" morph="HVqi3fs/Sp3ms">תִּדְּפֶ֥/נּוּ</w>';
chapter3 += '    <w lemma="7307" n="0" morph="HNcbsa">רֽוּחַ</w><seg type="x-sof-pasuq">׃</seg>';
chapter3 += '  </verse>';
chapter3 += '  <verse osisID="Ps.1.5">';
chapter3 += '    <w lemma="5921 a" morph="HC">עַל</w><seg type="x-maqqef">־</seg><w lemma="3651 c" n="1.0.0" morph="HC">כֵּ֤ן</w>';
chapter3 += '    <seg type="x-paseq">׀</seg>';
chapter3 += '    <w lemma="3808" morph="HTn">לֹא</w><seg type="x-maqqef">־</seg><w lemma="6965 b" morph="HVqi3mp">יָקֻ֣מוּ</w>';
chapter3 += '    <w lemma="7563" n="1.0" morph="HAampa">רְ֭שָׁעִים</w>';
chapter3 += '    <w lemma="b/4941" n="1" morph="HRd/Ncmsa">בַּ/מִּשְׁפָּ֑ט</w>';
chapter3 += '    <w lemma="c/2400" n="0.0" morph="HC/Aampa">וְ֝/חַטָּאִ֗ים</w>';
chapter3 += '    <w lemma="b/5712" morph="HR/Ncfsc">בַּ/עֲדַ֥ת</w>';
chapter3 += '    <w lemma="6662" n="0" morph="HAampa">צַדִּיקִֽים</w><seg type="x-sof-pasuq">׃</seg>';
chapter3 += '  </verse>';
chapter3 += '  <verse osisID="Ps.1.6">';
chapter3 += '    <w lemma="3588 a" morph="HC">כִּֽי</w><seg type="x-maqqef">־</seg><w lemma="3045" morph="HVqrms">יוֹדֵ֣עַ</w>';
chapter3 += '    <w lemma="3068" n="1.0" morph="HNp">יְ֭הוָה</w>';
chapter3 += '    <w lemma="1870" morph="HNcbsc">דֶּ֣רֶךְ</w>';
chapter3 += '    <w lemma="6662" n="1" morph="HAampa">צַדִּיקִ֑ים</w>';
chapter3 += '    <w lemma="c/1870" morph="HC/Ncbsc">וְ/דֶ֖רֶךְ</w>';
chapter3 += '    <w lemma="7563" morph="HAampa">רְשָׁעִ֣ים</w>';
chapter3 += '    <w lemma="6" n="0" morph="HVqi3fs">תֹּאבֵֽד</w><seg type="x-sof-pasuq">׃</seg>';
chapter3 += '  </verse>';
chapter3 += '</chapter>';