chapter3 = '<?xml version="1.0" encoding="UTF-8"?>';
chapter3 += '<chapter osisID="Ps.1">';
chapter3 += '	<verse osisID="Ps.1.1">';
chapter3 += '		<w lemma="835">אַ֥שְֽׁרֵי</w><seg type="x-maqqef">־</seg><w lemma="d/376" n="2.1">הָ/אִ֗ישׁ</w>';
chapter3 += '		<note n="c">We read one or more accents in L differently than BHS. Often this notation indicates a typographical error in BHS. </note>';
chapter3 += '		<w lemma="834 a" n="2.0.0">אֲשֶׁ֤ר</w>';
chapter3 += '		<seg type="x-paseq">׀</seg>';
chapter3 += '		<w lemma="3808">לֹ֥א</w>';
chapter3 += '		<w lemma="1980" n="2.0">הָלַךְ֮</w>';
chapter3 += '		<w lemma="b/6098">בַּ/עֲצַ֪ת</w>';
chapter3 += '		<w lemma="7563" n="2">רְשָׁ֫עִ֥ים</w>';
chapter3 += '		<w lemma="c/b/1870">וּ/בְ/דֶ֣רֶךְ</w>';
chapter3 += '		<w lemma="2400" n="1.0">חַ֭טָּאִים</w>';
chapter3 += '		<w lemma="3808">לֹ֥א</w>';
chapter3 += '		<w lemma="5975" n="1">עָמָ֑ד</w>';
chapter3 += '		<w lemma="c/b/4186">וּ/בְ/מוֹשַׁ֥ב</w>';
chapter3 += '		<w lemma="3887" n="0.0">לֵ֝צִ֗ים</w>';
chapter3 += '		<w lemma="3808">לֹ֣א</w>';
chapter3 += '		<w lemma="3427" n="0">יָשָֽׁב</w><seg type="x-sof-pasuq">׃</seg>';
chapter3 += '	</verse>';
chapter3 += '	<verse osisID="Ps.1.2">';
chapter3 += '		<w lemma="3588 a">כִּ֤י</w>';
chapter3 += '		<w lemma="518 a">אִ֥ם</w>';
chapter3 += '		<w lemma="b/8451">בְּ/תוֹרַ֥ת</w>';
chapter3 += '		<w lemma="3068" n="2.0">יְהוָ֗ה</w>';
chapter3 += '		<w lemma="2656" n="2">חֶ֫פְצ֥/וֹ</w>';
chapter3 += '		<w lemma="c/b/8451">וּֽ/בְ/תוֹרָת֥/וֹ</w>';
chapter3 += '		<w lemma="1897" n="1">יֶהְגֶּ֗ה</w>';
chapter3 += '		<w lemma="3119">יוֹמָ֥ם</w>';
chapter3 += '		<w lemma="c/3915" n="0">וָ/לָֽיְלָה</w><seg type="x-sof-pasuq">׃</seg>';
chapter3 += '	</verse>';
chapter3 += '	<verse osisID="Ps.1.3">';
chapter3 += '		<w lemma="c/1961" n="2.1">וְֽ/הָיָ֗ה</w>';
chapter3 += '		<w lemma="k/6086" n="2.0">כְּ/עֵץ֮</w>';
chapter3 += '		<w lemma="8362">שָׁת֪וּל</w>';
chapter3 += '		<w lemma="5921 a">עַֽל</w><seg type="x-maqqef">־</seg><w lemma="6388">פַּלְגֵ֫י</w>';
chapter3 += '		<w lemma="4325" n="2">מָ֥יִם</w>';
chapter3 += '		<w lemma="834 a">אֲשֶׁ֤ר</w>';
chapter3 += '		<w lemma="6529" n="1.0.0">פִּרְי֨/וֹ</w>';
chapter3 += '		<seg type="x-paseq">׀</seg>';
chapter3 += '		<w lemma="5414">יִתֵּ֬ן</w>';
chapter3 += '		<w lemma="b/6256" n="1.0">בְּ/עִתּ֗/וֹ</w>';
chapter3 += '		<w lemma="c/5929">וְ/עָלֵ֥/הוּ</w>';
chapter3 += '		<w lemma="3808">לֹֽא</w><seg type="x-maqqef">־</seg><w lemma="5034 b" n="1">יִבּ֑וֹל</w>';
chapter3 += '		<w lemma="c/3605">וְ/כֹ֖ל</w>';
chapter3 += '		<w lemma="834 a">אֲשֶׁר</w><seg type="x-maqqef">־</seg><w lemma="6213 a">יַעֲשֶׂ֣ה</w>';
chapter3 += '		<w lemma="6743 b" n="0">יַצְלִֽיחַ</w><seg type="x-sof-pasuq">׃</seg>';
chapter3 += '	</verse>';
chapter3 += '	<verse osisID="Ps.1.4">';
chapter3 += '		<w lemma="3808">לֹא</w><seg type="x-maqqef">־</seg><w lemma="3651 c">כֵ֥ן</w>';
chapter3 += '		<w lemma="d/7563" n="1">הָ/רְשָׁעִ֑ים</w>';
chapter3 += '		<w lemma="3588 b">כִּ֥י</w>';
chapter3 += '		<w lemma="518 b">אִם</w><seg type="x-maqqef">־</seg><w lemma="k/4671" n="0.0">כַּ֝/מֹּ֗ץ</w>';
chapter3 += '		<w lemma="834 a">אֲ‍ֽשֶׁר</w><seg type="x-maqqef">־</seg><w lemma="5086">תִּדְּפֶ֥/נּוּ</w>';
chapter3 += '		<w lemma="7307" n="0">רֽוּחַ</w><seg type="x-sof-pasuq">׃</seg>';
chapter3 += '	</verse>';
chapter3 += '	<verse osisID="Ps.1.5">';
chapter3 += '		<w lemma="5921 a">עַל</w><seg type="x-maqqef">־</seg><w lemma="3651 c" n="1.0.0">כֵּ֤ן</w>';
chapter3 += '		<seg type="x-paseq">׀</seg>';
chapter3 += '		<w lemma="3808">לֹא</w><seg type="x-maqqef">־</seg><w lemma="6965 b">יָקֻ֣מוּ</w>';
chapter3 += '		<w lemma="7563" n="1.0">רְ֭שָׁעִים</w>';
chapter3 += '		<w lemma="b/4941" n="1">בַּ/מִּשְׁפָּ֑ט</w>';
chapter3 += '		<w lemma="c/2400" n="0.0">וְ֝/חַטָּאִ֗ים</w>';
chapter3 += '		<w lemma="b/5712">בַּ/עֲדַ֥ת</w>';
chapter3 += '		<w lemma="6662" n="0">צַדִּיקִֽים</w><seg type="x-sof-pasuq">׃</seg>';
chapter3 += '	</verse>';
chapter3 += '	<verse osisID="Ps.1.6">';
chapter3 += '		<w lemma="3588 a">כִּֽי</w><seg type="x-maqqef">־</seg><w lemma="3045">יוֹדֵ֣עַ</w>';
chapter3 += '		<w lemma="3068" n="1.0">יְ֭הוָה</w>';
chapter3 += '		<w lemma="1870">דֶּ֣רֶךְ</w>';
chapter3 += '		<w lemma="6662" n="1">צַדִּיקִ֑ים</w>';
chapter3 += '		<w lemma="c/1870">וְ/דֶ֖רֶךְ</w>';
chapter3 += '		<w lemma="7563">רְשָׁעִ֣ים</w>';
chapter3 += '		<w lemma="6" n="0">תֹּאבֵֽד</w><seg type="x-sof-pasuq">׃</seg>';
chapter3 += '	</verse>';
chapter3 += '</chapter>';